"""Hand-curated vocabulary → phrase sequences for Lesson 3 Vocabulary Exhibition.

Kanji and content words are introduced individually; grammar folds into phrases.
If a word was already taught in this sequence, it reappears only inside a larger phrase.
"""

from __future__ import annotations

_P = {"phrase": True}

VOCABULARY_BY_SLUG: dict[str, list[dict]] = {
    "tongue": [
        {"jp": "縁側", "reading": "えんがわ", "en": "engawa (veranda)"},
        {"jp": "縁側に", "en": "upon the engawa", **_P},
        {"jp": "赤茶", "reading": "あかちゃ", "en": "reddish-brown"},
        {"jp": "犬", "reading": "いぬ", "en": "dog"},
        {"jp": "赤茶の犬", "en": "a reddish-brown dog", **_P},
        {"jp": "座る", "reading": "すわる", "en": "to sit"},
        {"jp": "座り", "en": "sat still", **_P},
        {"jp": "赤茶の犬が座り", "en": "a reddish-brown dog sat still", **_P},
        {"jp": "縁側に　赤茶の犬が座り", "en": "Upon the engawa a reddish-brown dog sat still", **_P},
        {"jp": "舌", "reading": "した", "en": "tongue"},
        {"jp": "伸ばす", "reading": "のばす", "en": "to stretch / extend"},
        {"jp": "伸ばした", "en": "outstretched", **_P},
        {"jp": "伸ばした舌", "en": "its outstretched tongue", **_P},
        {"jp": "だけ", "reading": "だけ", "en": "only"},
        {"jp": "伸ばした舌だけ", "en": "only its outstretched tongue", **_P},
        {"jp": "笑み", "reading": "えみ", "en": "smile"},
        {"jp": "伝える", "reading": "つたえる", "en": "to convey / carry"},
        {"jp": "笑みを伝えていた", "en": "carried the smile", **_P},
        {"jp": "伸ばした舌だけが　笑みを伝えていた", "en": "…while only its outstretched tongue carried the smile", **_P},
    ],
    "measuring_box": [
        {"jp": "木", "reading": "き", "en": "wooden"},
        {"jp": "升", "reading": "ます", "en": "measuring box / masu"},
        {"jp": "木の升", "en": "the wooden measure", **_P},
        {"jp": "木の升に", "en": "the wooden measure brimmed", **_P},
        {"jp": "白米", "reading": "しろまい", "en": "white rice"},
        {"jp": "満ちる", "reading": "みちる", "en": "to fill / brim"},
        {"jp": "溢れる", "reading": "あふれる", "en": "to overflow"},
        {"jp": "満ち溢れ", "en": "brimmed over", **_P},
        {"jp": "白米が満ち溢れ", "en": "white rice brimmed over", **_P},
        {"jp": "木の升に　白米が満ち溢れ", "en": "The wooden measure brimmed with white rice", **_P},
        {"jp": "朝", "reading": "あさ", "en": "morning"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "朝の光", "en": "the morning light", **_P},
        {"jp": "朝の光だけ", "en": "only the morning light", **_P},
        {"jp": "稲", "reading": "いね", "en": "rice / grain"},
        {"jp": "輝き", "reading": "かがやき", "en": "glow / radiance"},
        {"jp": "稲の輝き", "en": "the grain's glow", **_P},
        {"jp": "映す", "reading": "うつす", "en": "to mirror / reflect"},
        {"jp": "稲の輝きを映した", "en": "mirrored the grain's glow", **_P},
        {"jp": "朝の光だけが　稲の輝きを映した", "en": "…while only the morning light mirrored the grain's glow", **_P},
    ],
    "rise": [
        {"jp": "夕", "reading": "ゆう", "en": "evening"},
        {"jp": "空", "reading": "そら", "en": "sky"},
        {"jp": "夕空", "reading": "ゆうぞら", "en": "evening sky", **_P},
        {"jp": "夕空に", "en": "into the evening sky", **_P},
        {"jp": "灯籠", "reading": "とうろう", "en": "lantern"},
        {"jp": "次々", "reading": "つぎつぎ", "en": "one after another"},
        {"jp": "浮かぶ", "reading": "うかぶ", "en": "to rise / float up"},
        {"jp": "浮かび", "en": "rose", **_P},
        {"jp": "灯籠が次々と浮かび", "en": "the lanterns rose one by one", **_P},
        {"jp": "夕空に　灯籠が次々と浮かび", "en": "Into the evening sky the lanterns rose one by one", **_P},
        {"jp": "昇", "reading": "しょう", "en": "to rise / ascend"},
        {"jp": "坂", "reading": "さか", "en": "hillside / slope"},
        {"jp": "町", "reading": "まち", "en": "town"},
        {"jp": "坂の町", "en": "the hillside town", **_P},
        {"jp": "坂の町だけ", "en": "only the hillside town", **_P},
        {"jp": "橙", "reading": "だいだい", "en": "orange"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "橙の光", "en": "orange light", **_P},
        {"jp": "包む", "reading": "つつむ", "en": "to wrap / enfold"},
        {"jp": "橙の光に包まれた", "en": "wrapped itself in orange light", **_P},
        {"jp": "坂の町だけが　橙の光に包まれた", "en": "…while only the hillside town wrapped itself in orange light", **_P},
    ],
    "round": [
        {"jp": "満月", "reading": "まんげつ", "en": "full moon"},
        {"jp": "下", "reading": "もと", "en": "beneath / under"},
        {"jp": "満月の下", "en": "beneath the full moon", **_P},
        {"jp": "石畳", "reading": "いしだたみ", "en": "stone pavement"},
        {"jp": "道", "reading": "みち", "en": "path / road"},
        {"jp": "石畳の道", "en": "the stone path", **_P},
        {"jp": "続く", "reading": "つづく", "en": "to continue / wind on"},
        {"jp": "続き", "en": "wound on", **_P},
        {"jp": "石畳の道が続き", "en": "the stone path wound on", **_P},
        {"jp": "満月の下　石畳の道が続き", "en": "Beneath the full moon the stone path wound on", **_P},
        {"jp": "丸", "reading": "まる", "en": "round / circle"},
        {"jp": "障子", "reading": "しょうじ", "en": "shoji (paper screen door)"},
        {"jp": "灯り", "reading": "あかり", "en": "light / glow"},
        {"jp": "障子の灯り", "en": "light through the shoji", **_P},
        {"jp": "障子の灯りだけ", "en": "only the light through shoji", **_P},
        {"jp": "夜", "reading": "よる", "en": "night"},
        {"jp": "温める", "reading": "あたためる", "en": "to warm"},
        {"jp": "夜を温めていた", "en": "warmed the night", **_P},
        {"jp": "障子の灯りだけが　夜を温めていた", "en": "…while only the light through shoji warmed the night", **_P},
    ],
    "measurement": [
        {"jp": "指先", "reading": "ゆびさき", "en": "fingertip"},
        {"jp": "指先で", "en": "at his fingertips", **_P},
        {"jp": "小さな", "reading": "ちいさな", "en": "tiny / small"},
        {"jp": "楔", "reading": "くさび", "en": "peg / wedge"},
        {"jp": "小さな楔", "en": "a tiny peg", **_P},
        {"jp": "打ち込む", "reading": "うちこむ", "en": "to drive in"},
        {"jp": "打ち込み", "en": "drove in", **_P},
        {"jp": "小さな楔を打ち込み", "en": "he drove a tiny peg", **_P},
        {"jp": "指先で　小さな楔を打ち込み", "en": "At his fingertips he drove a tiny peg", **_P},
        {"jp": "寸", "reading": "すん", "en": "measurement / inch"},
        {"jp": "匠", "reading": "たくみ", "en": "master craftsman"},
        {"jp": "文字", "reading": "もじ", "en": "character"},
        {"jp": "「匠」の文字", "en": "the character for master craftsman", **_P},
        {"jp": "「匠」の文字だけ", "en": "only the character for master craftsman", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / silent"},
        {"jp": "見守る", "reading": "みまもる", "en": "to watch over"},
        {"jp": "静かに見守っていた", "en": "watched in silence", **_P},
        {"jp": "「匠」の文字だけが　静かに見守っていた", "en": "…while only the character for master craftsman watched in silence", **_P},
    ],
    "elbow": [
        {"jp": "縁側", "reading": "えんがわ", "en": "engawa (veranda)"},
        {"jp": "もたれる", "reading": "もたれる", "en": "to lean against"},
        {"jp": "もたれ", "en": "leaning", **_P},
        {"jp": "縁側にもたれ", "en": "leaning on the engawa", **_P},
        {"jp": "頬杖", "reading": "ほおづえ", "en": "elbow rest / cheek on hand"},
        {"jp": "つく", "reading": "つく", "en": "to rest (on one's elbow)"},
        {"jp": "頬杖をつき", "en": "rested on her elbow", **_P},
        {"jp": "縁側にもたれ　頬杖をつき", "en": "Leaning on the engawa she rested on her elbow", **_P},
        {"jp": "肘", "reading": "ひじ", "en": "elbow"},
        {"jp": "庭", "reading": "にわ", "en": "garden"},
        {"jp": "灯籠", "reading": "とうろう", "en": "lantern"},
        {"jp": "庭の灯籠", "en": "the garden lantern", **_P},
        {"jp": "庭の灯籠だけ", "en": "only the garden lantern", **_P},
        {"jp": "午後", "reading": "ごご", "en": "afternoon"},
        {"jp": "映す", "reading": "うつす", "en": "to mirror / reflect"},
        {"jp": "午後を映していた", "en": "mirrored the afternoon", **_P},
        {"jp": "庭の灯籠だけが　午後を映していた", "en": "…while only the garden lantern mirrored the afternoon", **_P},
    ],
    "specialty": [
        {"jp": "工", "reading": "こう", "en": "craft / artisan work"},
        {"jp": "房", "reading": "ぼう", "en": "room / workshop"},
        {"jp": "工房", "reading": "こうぼう", "en": "workshop", **_P},
        {"jp": "床", "reading": "ゆか", "en": "floor"},
        {"jp": "工房の床", "en": "the workshop floor", **_P},
        {"jp": "工房の床に", "en": "upon the workshop floor", **_P},
        {"jp": "削る", "reading": "けずる", "en": "to shave / plane (wood)"},
        {"jp": "屑", "reading": "くず", "en": "shavings / scraps"},
        {"jp": "削り屑", "reading": "けずりくず", "en": "wood shavings", **_P},
        {"jp": "積もる", "reading": "つもる", "en": "to gather / pile up"},
        {"jp": "積もり", "en": "gathered", **_P},
        {"jp": "削り屑が積もり", "en": "wood shavings gathered", **_P},
        {"jp": "工房の床に　削り屑が積もり", "en": "Wood shavings gathered upon the workshop floor", **_P},
        {"jp": "老いる", "reading": "おいる", "en": "to age / grow old"},
        {"jp": "老いた", "en": "aged", **_P},
        {"jp": "職人", "reading": "しょくにん", "en": "craftsman"},
        {"jp": "老いた職人", "en": "the aged craftsman", **_P},
        {"jp": "老いた職人だけ", "en": "only the aged craftsman", **_P},
        {"jp": "技", "reading": "わざ", "en": "skill / craft"},
        {"jp": "研ぐ", "reading": "みがく", "en": "to hone / polish"},
        {"jp": "技を研いでいた", "en": "honed his skill", **_P},
        {"jp": "老いた職人だけが　技を研いでいた", "en": "…while only the aged craftsman honed his skill", **_P},
    ],
    "knowledgeable": [
        {"jp": "本棚", "reading": "ほんだな", "en": "bookshelf"},
        {"jp": "囲む", "reading": "かこむ", "en": "to surround"},
        {"jp": "囲まれ", "en": "surrounded", **_P},
        {"jp": "本棚に囲まれ", "en": "surrounded by shelves", **_P},
        {"jp": "老人", "reading": "ろうじん", "en": "old man"},
        {"jp": "筆", "reading": "ふで", "en": "brush (for writing)"},
        {"jp": "執る", "reading": "とる", "en": "to hold / take up"},
        {"jp": "筆を執り", "en": "held his brush", **_P},
        {"jp": "老人が筆を執り", "en": "the old man held his brush", **_P},
        {"jp": "本棚に囲まれ　老人が筆を執り", "en": "Surrounded by shelves the old man held his brush", **_P},
        {"jp": "知", "reading": "ち", "en": "knowledge"},
        {"jp": "差し込む", "reading": "さしこむ", "en": "to stream in"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "差し込む光", "en": "the light streaming in", **_P},
        {"jp": "差し込む光だけ", "en": "only the light streaming in", **_P},
        {"jp": "照らす", "reading": "てらす", "en": "to illuminate"},
        {"jp": "知を照らしていた", "en": "illuminated his knowledge", **_P},
        {"jp": "差し込む光だけが　知を照らしていた", "en": "…while only the light streaming in illuminated his knowledge", **_P},
    ],
    "signal": [
        {"jp": "石", "reading": "いし", "en": "stone"},
        {"jp": "上", "reading": "うえ", "en": "upon / above"},
        {"jp": "石上", "reading": "いしのうえ", "en": "upon the stones", **_P},
        {"jp": "石上に", "en": "upon the stones", **_P},
        {"jp": "卜", "reading": "ぼく", "en": "divining rod"},
        {"jp": "枝", "reading": "えだ", "en": "branch / twig"},
        {"jp": "卜の枝", "en": "a divining rod", **_P},
        {"jp": "立つ", "reading": "たつ", "en": "to stand"},
        {"jp": "立ち", "en": "stood tall", **_P},
        {"jp": "卜の枝が立ち", "en": "a divining rod stood tall", **_P},
        {"jp": "石上に　卜の枝が立ち", "en": "Upon the stones a divining rod stood tall", **_P},
        {"jp": "兆", "reading": "ちょう", "en": "sign / omen / signal"},
        {"jp": "夕陽", "reading": "ゆうひ", "en": "setting sun"},
        {"jp": "夕陽だけ", "en": "only the setting sun", **_P},
        {"jp": "山", "reading": "やま", "en": "mountain"},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "照らす", "reading": "てらす", "en": "to light / illuminate"},
        {"jp": "山を静かに照らした", "en": "quietly lit the mountains", **_P},
        {"jp": "夕陽だけが　山を静かに照らした", "en": "…while only the setting sun quietly lit the mountains", **_P},
    ],
    "fortune_telling": [
        {"jp": "神社", "reading": "じんじゃ", "en": "shrine"},
        {"jp": "枝", "reading": "えだ", "en": "branch"},
        {"jp": "神社の枝", "en": "the shrine branch", **_P},
        {"jp": "神社の枝に", "en": "upon the shrine branch", **_P},
        {"jp": "おみくじ", "reading": "おみくじ", "en": "fortune slip (omikuji)"},
        {"jp": "結ぶ", "reading": "むすぶ", "en": "to tie"},
        {"jp": "結ばれ", "en": "were tied", **_P},
        {"jp": "おみくじが結ばれ", "en": "omikuji slips were tied", **_P},
        {"jp": "神社の枝に　おみくじが結ばれ", "en": "Upon the shrine branch omikuji slips were tied", **_P},
        {"jp": "占", "reading": "うらない", "en": "fortune telling / divination"},
        {"jp": "夕光", "reading": "ゆうこう", "en": "evening light"},
        {"jp": "夕光だけ", "en": "only the evening light", **_P},
        {"jp": "運命", "reading": "うんめい", "en": "fate / destiny"},
        {"jp": "漂わせる", "reading": "ただよわせる", "en": "to drift over"},
        {"jp": "運命を漂わせた", "en": "drifted over fate", **_P},
        {"jp": "夕光だけが　運命を漂わせた", "en": "…while only the evening light drifted over fate", **_P},
    ],
    "up": [
        {"jp": "青", "reading": "あお", "en": "blue"},
        {"jp": "空", "reading": "そら", "en": "sky"},
        {"jp": "青空", "reading": "あおぞら", "en": "blue sky", **_P},
        {"jp": "青空に", "en": "against the blue sky", **_P},
        {"jp": "幟", "reading": "のぼり", "en": "banner"},
        {"jp": "凧", "reading": "たこ", "en": "kite"},
        {"jp": "幟の凧", "en": "a banner kite", **_P},
        {"jp": "舞う", "reading": "まう", "en": "to dance / flutter"},
        {"jp": "舞い", "en": "danced", **_P},
        {"jp": "幟の凧が舞い", "en": "a banner kite danced", **_P},
        {"jp": "青空に　幟の凧が舞い", "en": "Against the blue sky a banner kite danced", **_P},
        {"jp": "上", "reading": "うえ", "en": "up / above"},
        {"jp": "長い", "reading": "ながい", "en": "long"},
        {"jp": "糸", "reading": "いと", "en": "string / thread"},
        {"jp": "長い糸", "en": "its long string", **_P},
        {"jp": "長い糸だけ", "en": "only its long string", **_P},
        {"jp": "地面", "reading": "じめん", "en": "ground / earth"},
        {"jp": "つなぐ", "reading": "つなぐ", "en": "to connect"},
        {"jp": "地面とつないでいた", "en": "connected to the earth", **_P},
        {"jp": "長い糸だけが　地面とつないでいた", "en": "…while only its long string connected to the earth", **_P},
    ],
    "below": [
        {"jp": "石段", "reading": "いしだん", "en": "stone step"},
        {"jp": "下", "reading": "した", "en": "below / beneath"},
        {"jp": "石段の下", "en": "beneath the stone step", **_P},
        {"jp": "猫", "reading": "ねこ", "en": "cat"},
        {"jp": "丸い", "reading": "まるい", "en": "round"},
        {"jp": "丸く", "en": "round", **_P},
        {"jp": "丸くなる", "reading": "まるくなる", "en": "to curl up"},
        {"jp": "丸くなり", "en": "curled round", **_P},
        {"jp": "猫が丸くなり", "en": "the cat curled round", **_P},
        {"jp": "石段の下　猫が丸くなり", "en": "Beneath the stone step the cat curled round", **_P},
        {"jp": "朝日", "reading": "あさひ", "en": "morning sun"},
        {"jp": "朝日だけ", "en": "only the morning sun", **_P},
        {"jp": "参道", "reading": "さんどう", "en": "shrine path"},
        {"jp": "照らす", "reading": "てらす", "en": "to light / illuminate"},
        {"jp": "参道を照らしていた", "en": "lit the shrine path", **_P},
        {"jp": "朝日だけが　参道を照らしていた", "en": "…while only the morning sun lit the shrine path", **_P},
    ],
    "eminent": [
        {"jp": "床の間", "reading": "とこのま", "en": "tokonoma (alcove)"},
        {"jp": "床の間に", "en": "within the tokonoma", **_P},
        {"jp": "梅", "reading": "うめ", "en": "plum"},
        {"jp": "椿", "reading": "つばき", "en": "camellia"},
        {"jp": "梅と椿", "en": "plum and camellia", **_P},
        {"jp": "置く", "reading": "おく", "en": "to place"},
        {"jp": "置かれ", "en": "were placed", **_P},
        {"jp": "梅と椿が置かれ", "en": "plum and camellia were placed", **_P},
        {"jp": "床の間に　梅と椿が置かれ", "en": "Within the tokonoma plum and camellia were placed", **_P},
        {"jp": "卓", "reading": "たく", "en": "eminent / alcove stand"},
        {"jp": "余白", "reading": "よはく", "en": "open space / blank margin"},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "余白の静けさ", "en": "the stillness of open space", **_P},
        {"jp": "余白の静けさだけ", "en": "only the stillness of open space", **_P},
        {"jp": "研ぐ", "reading": "みがく", "en": "to refine / polish"},
        {"jp": "卓を研いでいた", "en": "refined the alcove", **_P},
        {"jp": "余白の静けさだけが　卓を研いでいた", "en": "…while only the stillness of open space refined the alcove", **_P},
    ],
    "morning": [
        {"jp": "茅葺", "reading": "かやぶき", "en": "thatched"},
        {"jp": "里", "reading": "さと", "en": "village"},
        {"jp": "茅葺の里", "en": "the thatched village", **_P},
        {"jp": "茅葺の里に", "en": "into the thatched village", **_P},
        {"jp": "朝日", "reading": "あさひ", "en": "morning sun"},
        {"jp": "差し込む", "reading": "さしこむ", "en": "to stream in"},
        {"jp": "差し込み", "en": "streamed", **_P},
        {"jp": "朝日が差し込み", "en": "the morning sun streamed", **_P},
        {"jp": "茅葺の里に　朝日が差し込み", "en": "Into the thatched village the morning sun streamed", **_P},
        {"jp": "朝", "reading": "あさ", "en": "morning"},
        {"jp": "谷", "reading": "たに", "en": "valley"},
        {"jp": "霧", "reading": "きり", "en": "mist"},
        {"jp": "谷の霧", "en": "the valley mist", **_P},
        {"jp": "谷の霧だけ", "en": "only the valley mist", **_P},
        {"jp": "黄金", "reading": "おうごん", "en": "gold / golden"},
        {"jp": "染まる", "reading": "そまる", "en": "to be dyed / turn"},
        {"jp": "黄金に染まっていた", "en": "turned to gold", **_P},
        {"jp": "谷の霧だけが　黄金に染まっていた", "en": "…while only the valley mist turned to gold", **_P},
    ],
    "derision": [
        {"jp": "門", "reading": "もん", "en": "gate"},
        {"jp": "隙間", "reading": "すきま", "en": "gap / narrow opening"},
        {"jp": "門の隙間", "en": "the gate's narrow gap", **_P},
        {"jp": "門の隙間に", "en": "through the gate's narrow gap", **_P},
        {"jp": "三人", "reading": "さんにん", "en": "three people"},
        {"jp": "子", "reading": "こ", "en": "child"},
        {"jp": "三人の子", "en": "three children", **_P},
        {"jp": "覗く", "reading": "のぞく", "en": "to peer / peek"},
        {"jp": "覗き", "en": "peered", **_P},
        {"jp": "三人の子が覗き", "en": "three children peered", **_P},
        {"jp": "門の隙間に　三人の子が覗き", "en": "Through the gate's narrow gap three children peered", **_P},
        {"jp": "戯", "reading": "ぎ", "en": "derision / jest"},
        {"jp": "押さえる", "reading": "おさえる", "en": "to cover / hold back"},
        {"jp": "押さえた", "en": "covered", **_P},
        {"jp": "口", "reading": "くち", "en": "mouth"},
        {"jp": "押さえた口", "en": "their covered mouths", **_P},
        {"jp": "押さえた口だけ", "en": "only their covered mouths", **_P},
        {"jp": "笑い", "reading": "わらい", "en": "laughter"},
        {"jp": "隠す", "reading": "かくす", "en": "to hide"},
        {"jp": "笑いを隠していた", "en": "hid the laughter", **_P},
        {"jp": "押さえた口だけが　笑いを隠していた", "en": "…while only their covered mouths hid the laughter", **_P},
    ],
    "only": [
        {"jp": "点てる", "reading": "たてる", "en": "to whisk (tea)"},
        {"jp": "前", "reading": "まえ", "en": "before"},
        {"jp": "点てる前", "en": "before whisking tea", **_P},
        {"jp": "点てる前に", "en": "before whisking tea", **_P},
        {"jp": "一本", "reading": "いっぽん", "en": "one (finger)"},
        {"jp": "指", "reading": "ゆび", "en": "finger"},
        {"jp": "一本の指", "en": "a single finger", **_P},
        {"jp": "立つ", "reading": "たつ", "en": "to rise / stand up"},
        {"jp": "立ち", "en": "rose", **_P},
        {"jp": "一本の指が立ち", "en": "a single finger rose", **_P},
        {"jp": "点てる前に　一本の指が立ち", "en": "Before whisking tea a single finger rose", **_P},
        {"jp": "唯", "reading": "ただ", "en": "only / merely"},
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "気配", "reading": "けはい", "en": "presence / air"},
        {"jp": "静かな気配", "en": "a quiet presence", **_P},
        {"jp": "静かな気配だけ", "en": "only the quiet presence", **_P},
        {"jp": "室", "reading": "しつ", "en": "room"},
        {"jp": "包む", "reading": "つつむ", "en": "to fill / enfold"},
        {"jp": "室を包んでいた", "en": "filled the room", **_P},
        {"jp": "静かな気配だけが　室を包んでいた", "en": "…while only the quiet presence filled the room", **_P},
    ],
    "shellfish": [
        {"jp": "岩場", "reading": "いわば", "en": "rocky shore"},
        {"jp": "岩場で", "en": "upon the rocky shore", **_P},
        {"jp": "少女", "reading": "しょうじょ", "en": "girl"},
        {"jp": "貝", "reading": "かい", "en": "shell / shellfish"},
        {"jp": "掌", "reading": "てのひら", "en": "palm (of hand)"},
        {"jp": "貝を掌に", "en": "cradled a shell in her palm", **_P},
        {"jp": "少女が貝を掌に", "en": "the girl cradled a shell in her palm", **_P},
        {"jp": "岩場で　少女が貝を掌に", "en": "Upon the rocky shore the girl cradled a shell", **_P},
        {"jp": "波", "reading": "なみ", "en": "wave / sea"},
        {"jp": "記憶", "reading": "きおく", "en": "memory"},
        {"jp": "波の記憶", "en": "the sea's memory", **_P},
        {"jp": "波の記憶だけ", "en": "only the sea's memory", **_P},
        {"jp": "微笑み", "reading": "ほほえみ", "en": "smile"},
        {"jp": "残る", "reading": "のこる", "en": "to linger / remain"},
        {"jp": "微笑みに残っていた", "en": "lingered in her smile", **_P},
        {"jp": "波の記憶だけが　微笑みに残っていた", "en": "…while only the sea's memory lingered in her smile", **_P},
    ],
    "pop_song": [
        {"jp": "畳", "reading": "たたみ", "en": "tatami"},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "畳の部屋", "en": "the tatami room", **_P},
        {"jp": "畳の部屋で", "en": "in the tatami room", **_P},
        {"jp": "ヘアブラシ", "reading": "ヘアブラシ", "en": "hairbrush"},
        {"jp": "マイク", "reading": "マイク", "en": "microphone"},
        {"jp": "ヘアブラシをマイクに", "en": "into a hairbrush as a microphone", **_P},
        {"jp": "畳の部屋で　ヘアブラシをマイクに", "en": "In the tatami room she sang into a hairbrush", **_P},
        {"jp": "唱", "reading": "しょう", "en": "to sing / chant"},
        {"jp": "幼い", "reading": "おさない", "en": "young / childlike"},
        {"jp": "声", "reading": "こえ", "en": "voice"},
        {"jp": "幼い声", "en": "a child's voice", **_P},
        {"jp": "幼い声だけ", "en": "only a child's voice", **_P},
        {"jp": "夕", "reading": "ゆう", "en": "evening"},
        {"jp": "明るい", "reading": "あかるい", "en": "bright"},
        {"jp": "明るく", "en": "brightened", **_P},
        {"jp": "夕を明るくした", "en": "brightened the evening", **_P},
        {"jp": "幼い声だけが　夕を明るくした", "en": "…while only a child's voice brightened the evening", **_P},
    ],
    "virtue": [
        {"jp": "雪", "reading": "ゆき", "en": "snow / snowy"},
        {"jp": "参道", "reading": "さんどう", "en": "shrine path"},
        {"jp": "雪の参道", "en": "the snowy shrine path", **_P},
        {"jp": "雪の参道に", "en": "upon the snowy shrine path", **_P},
        {"jp": "武士", "reading": "ぶし", "en": "samurai / warrior"},
        {"jp": "立つ", "reading": "たつ", "en": "to stand"},
        {"jp": "立ち", "en": "stood", **_P},
        {"jp": "武士が立ち", "en": "the samurai stood", **_P},
        {"jp": "雪の参道に　武士が立ち", "en": "Upon the snowy shrine path the samurai stood", **_P},
        {"jp": "徳", "reading": "とく", "en": "virtue / moral integrity"},
        {"jp": "揺るぎぬ", "reading": "ゆるぎぬ", "en": "unwavering"},
        {"jp": "姿", "reading": "すがた", "en": "form / figure"},
        {"jp": "揺るぎぬ姿", "en": "his unwavering form", **_P},
        {"jp": "揺るぎぬ姿だけ", "en": "only his unwavering form", **_P},
        {"jp": "灯籠", "reading": "とうろう", "en": "lantern"},
        {"jp": "映る", "reading": "うつる", "en": "to reflect"},
        {"jp": "灯籠に映った", "en": "reflected in the lanterns", **_P},
        {"jp": "揺るぎぬ姿だけが　灯籠に映った", "en": "…while only his unwavering form reflected in the lanterns", **_P},
    ],
    "employee": [
        {"jp": "紺", "reading": "こん", "en": "indigo"},
        {"jp": "作務衣", "reading": "さむえ", "en": "samue (work clothes)"},
        {"jp": "紺の作務衣", "en": "indigo samue", **_P},
        {"jp": "紺の作務衣に", "en": "in indigo samue", **_P},
        {"jp": "四人", "reading": "よにん", "en": "four people"},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to line up / stand side by side"},
        {"jp": "並び", "en": "stood side by side", **_P},
        {"jp": "四人が並び", "en": "four stood side by side", **_P},
        {"jp": "紺の作務衣に　四人が並び", "en": "In indigo samue four stood side by side", **_P},
        {"jp": "員", "reading": "いん", "en": "member / employee"},
        {"jp": "縁側", "reading": "えんがわ", "en": "engawa (veranda)"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "縁側の光", "en": "light from the engawa", **_P},
        {"jp": "縁側の光だけ", "en": "only the light from the engawa", **_P},
        {"jp": "職", "reading": "しょく", "en": "work / occupation"},
        {"jp": "温める", "reading": "あたためる", "en": "to warm"},
        {"jp": "職を温めていた", "en": "warmed their work", **_P},
        {"jp": "縁側の光だけが　職を温めていた", "en": "…while only the light from the engawa warmed their work", **_P},
    ],
}
