"""Hand-curated vocabulary → phrase sequences for Lesson 4 Vocabulary Exhibition.

Kanji and content words are introduced individually; grammar folds into phrases.
If a word was already taught in this sequence, it reappears only inside a larger phrase.
Four-line verses: build lines 1–2, introduce target kanji, then build lines 3–4.
"""

from __future__ import annotations

_P = {"phrase": True}

VOCABULARY_BY_SLUG: dict[str, list[dict]] = {
    "post_a_bill": [
        {"jp": "白い", "reading": "しろい", "en": "white / blank"},
        {"jp": "紙", "reading": "かみ", "en": "paper / sheet"},
        {"jp": "白い紙", "en": "a blank sheet", **_P},
        {"jp": "白い紙を", "en": "a blank sheet", **_P},
        {"jp": "壁", "reading": "かべ", "en": "wall"},
        {"jp": "押し当てる", "reading": "おしあてる", "en": "to press against"},
        {"jp": "押し当て", "en": "pressed against", **_P},
        {"jp": "壁へ押し当て", "en": "pressed against the wall", **_P},
        {"jp": "白い紙を　壁へ押し当て", "en": "A blank sheet was pressed against the wall", **_P},
        {"jp": "貼", "reading": "はる", "en": "to post / paste"},
        {"jp": "誰か", "reading": "だれか", "en": "someone"},
        {"jp": "言葉", "reading": "ことば", "en": "message / words"},
        {"jp": "誰かの言葉", "en": "someone's message", **_P},
        {"jp": "誰かの言葉が", "en": "someone's message", **_P},
        {"jp": "街", "reading": "まち", "en": "street / town"},
        {"jp": "貼られてゆく", "en": "became part of", **_P},
        {"jp": "街に貼られてゆく", "en": "became part of the street", **_P},
        {"jp": "誰かの言葉が　街に貼られてゆく", "en": "…and someone's message became part of the street", **_P},
    ],
    "see": [
        {"jp": "遠い", "reading": "とおい", "en": "distant"},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "遠い影", "en": "a distant shadow", **_P},
        {"jp": "遠い影を", "en": "a distant shadow", **_P},
        {"jp": "目", "reading": "め", "en": "eyes"},
        {"jp": "細める", "reading": "ほそめる", "en": "to narrow"},
        {"jp": "目を細めて", "en": "narrowed my eyes", **_P},
        {"jp": "追う", "reading": "おう", "en": "to follow / chase"},
        {"jp": "追えば", "en": "to follow", **_P},
        {"jp": "目を細めて追えば", "en": "When I narrowed my eyes to follow", **_P},
        {"jp": "遠い影を　目を細めて追えば", "en": "When I narrowed my eyes to follow a distant shadow", **_P},
        {"jp": "見", "reading": "み", "en": "to see / look"},
        {"jp": "まだ", "reading": "まだ", "en": "still / yet"},
        {"jp": "知る", "reading": "しる", "en": "to know"},
        {"jp": "知らぬ", "en": "unknown", **_P},
        {"jp": "世界", "reading": "せかい", "en": "world"},
        {"jp": "まだ知らぬ世界", "en": "an unknown world", **_P},
        {"jp": "まだ知らぬ世界が", "en": "an unknown world", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "動く", "reading": "うごく", "en": "to stir / move"},
        {"jp": "動いていた", "en": "was stirring", **_P},
        {"jp": "静かに動いていた", "en": "was quietly stirring", **_P},
        {"jp": "まだ知らぬ世界が　静かに動いていた", "en": "…an unknown world was quietly stirring", **_P},
    ],
    "newborn": [
        {"jp": "小さな", "reading": "ちいさな", "en": "tiny"},
        {"jp": "指", "reading": "ゆび", "en": "finger"},
        {"jp": "小さな指", "en": "a tiny finger", **_P},
        {"jp": "小さな指が", "en": "a tiny finger", **_P},
        {"jp": "そっと", "reading": "そっと", "en": "gently"},
        {"jp": "握り返す", "reading": "にぎりかえす", "en": "to curl around / grip back"},
        {"jp": "握り返し", "en": "curled around", **_P},
        {"jp": "そっと握り返し", "en": "gently curled around", **_P},
        {"jp": "小さな指が　そっと握り返し", "en": "A tiny finger gently curled around mine", **_P},
        {"jp": "産", "reading": "うむ", "en": "to give birth / bring forth"},
        {"jp": "新しい", "reading": "あたらしい", "en": "new"},
        {"jp": "命", "reading": "いのち", "en": "life"},
        {"jp": "新しい命", "en": "a new life", **_P},
        {"jp": "新しい命が", "en": "a new life", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "始まる", "reading": "はじまる", "en": "to begin"},
        {"jp": "静かに始まる", "en": "quietly began", **_P},
        {"jp": "新しい命が　静かに始まる", "en": "…as a new life quietly began", **_P},
    ],
    "beginning": [
        {"jp": "朝焼け", "reading": "あさやけ", "en": "morning glow"},
        {"jp": "富士", "reading": "ふじ", "en": "Mount Fuji"},
        {"jp": "朝焼けの富士", "en": "Mount Fuji in the morning glow", **_P},
        {"jp": "朝焼けの富士を", "en": "Mount Fuji in the morning glow", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "見つめる", "reading": "みつめる", "en": "to gaze at"},
        {"jp": "見つめ", "en": "gazing", **_P},
        {"jp": "静かに見つめ", "en": "gazing quietly", **_P},
        {"jp": "朝焼けの富士を　静かに見つめ", "en": "Gazing quietly at Mount Fuji in the morning glow", **_P},
        {"jp": "始", "reading": "はじ", "en": "to begin / start"},
        {"jp": "すべて", "reading": "すべて", "en": "every / all"},
        {"jp": "始まり", "reading": "はじまり", "en": "beginning"},
        {"jp": "すべての始まり", "en": "every beginning", **_P},
        {"jp": "すべての始まりが", "en": "every beginning", **_P},
        {"jp": "水面", "reading": "すいめん", "en": "water's surface"},
        {"jp": "映る", "reading": "うつる", "en": "to reflect"},
        {"jp": "映っていた", "en": "was reflected", **_P},
        {"jp": "水面に映っていた", "en": "reflected upon the water", **_P},
        {"jp": "すべての始まりが　水面に映っていた", "en": "…every beginning was reflected upon the water", **_P},
    ],
    "page": [
        {"jp": "古い", "reading": "ふるい", "en": "old"},
        {"jp": "屋根裏", "reading": "やねうら", "en": "attic"},
        {"jp": "古い屋根裏", "en": "the old attic", **_P},
        {"jp": "古い屋根裏で", "en": "in the old attic", **_P},
        {"jp": "本", "reading": "ほん", "en": "book"},
        {"jp": "開ける", "reading": "あける", "en": "to open"},
        {"jp": "開けば", "en": "opening", **_P},
        {"jp": "本を開けば", "en": "opening a book", **_P},
        {"jp": "古い屋根裏で　本を開けば", "en": "In the old attic, opening a book", **_P},
        {"jp": "頁", "reading": "ページ", "en": "page"},
        {"jp": "一枚", "reading": "いちまい", "en": "a single (sheet)"},
        {"jp": "一枚の頁", "en": "a single page", **_P},
        {"jp": "一枚の頁が", "en": "a single page", **_P},
        {"jp": "時", "reading": "とき", "en": "time"},
        {"jp": "呼び覚ます", "reading": "よびさます", "en": "to wake / call forth"},
        {"jp": "呼び覚ましていた", "en": "was waking", **_P},
        {"jp": "時を呼び覚ましていた", "en": "was waking time itself", **_P},
        {"jp": "一枚の頁が　時を呼び覚ましていた", "en": "…a single page was waking time itself", **_P},
    ],
    "stubborn": [
        {"jp": "腕", "reading": "うで", "en": "arm"},
        {"jp": "組む", "reading": "くむ", "en": "to fold / cross"},
        {"jp": "組んだ", "en": "with folded", **_P},
        {"jp": "腕を組んだ", "en": "with folded arms", **_P},
        {"jp": "小さな", "reading": "ちいさな", "en": "small"},
        {"jp": "顔", "reading": "かお", "en": "face"},
        {"jp": "小さな顔", "en": "the small face", **_P},
        {"jp": "小さな顔に", "en": "upon the small face", **_P},
        {"jp": "腕を組んだ　小さな顔に", "en": "Upon the small face with folded arms", **_P},
        {"jp": "頑", "reading": "がん", "en": "stubborn / obstinate"},
        {"jp": "譲る", "reading": "ゆずる", "en": "to yield / give way"},
        {"jp": "譲らぬ", "en": "unyielding", **_P},
        {"jp": "気持ち", "reading": "きもち", "en": "spirit / feeling"},
        {"jp": "譲らぬ気持ち", "en": "an unyielding spirit", **_P},
        {"jp": "譲らぬ気持ちが", "en": "an unyielding spirit", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "燃える", "reading": "もえる", "en": "to burn"},
        {"jp": "燃えていた", "en": "was burning", **_P},
        {"jp": "静かに燃えていた", "en": "was quietly burning", **_P},
        {"jp": "譲らぬ気持ちが　静かに燃えていた", "en": "…an unyielding spirit was quietly burning", **_P},
    ],
    "mediocre": [
        {"jp": "積み上がる", "reading": "つみあがる", "en": "to pile up"},
        {"jp": "書類", "reading": "しょるい", "en": "documents"},
        {"jp": "積み上がる書類", "en": "piled documents", **_P},
        {"jp": "積み上がる書類の", "en": "beyond the piled documents", **_P},
        {"jp": "向こう", "reading": "むこう", "en": "beyond / on the other side"},
        {"jp": "向こうで", "en": "beyond", **_P},
        {"jp": "積み上がる書類の　向こうで", "en": "Beyond the piled documents", **_P},
        {"jp": "凡", "reading": "ぼん", "en": "mediocre / ordinary"},
        {"jp": "疲れた", "reading": "つかれた", "en": "tired"},
        {"jp": "視線", "reading": "しせん", "en": "gaze / eyes"},
        {"jp": "疲れた視線", "en": "tired eyes", **_P},
        {"jp": "疲れた視線が", "en": "tired eyes", **_P},
        {"jp": "灯り", "reading": "あかり", "en": "lamplight"},
        {"jp": "沈む", "reading": "しずむ", "en": "to sink"},
        {"jp": "沈んでいた", "en": "were sinking", **_P},
        {"jp": "灯りに沈んでいた", "en": "were sinking into the lamplight", **_P},
        {"jp": "疲れた視線が　灯りに沈んでいた", "en": "…tired eyes were sinking into the lamplight", **_P},
    ],
    "defeat": [
        {"jp": "うつむく", "reading": "うつむく", "en": "to bow one's head"},
        {"jp": "うつむいた", "en": "bowed", **_P},
        {"jp": "肩", "reading": "かた", "en": "shoulders"},
        {"jp": "うつむいた肩", "en": "bowed shoulders", **_P},
        {"jp": "うつむいた肩に", "en": "upon bowed shoulders", **_P},
        {"jp": "汗", "reading": "あせ", "en": "sweat"},
        {"jp": "落ちる", "reading": "おちる", "en": "to fall"},
        {"jp": "落ち", "en": "fell", **_P},
        {"jp": "汗が落ち", "en": "sweat fell", **_P},
        {"jp": "うつむいた肩に　汗が落ち", "en": "Sweat fell upon bowed shoulders", **_P},
        {"jp": "敗", "reading": "はい", "en": "defeat / loss"},
        {"jp": "敗北", "reading": "はいぼく", "en": "defeat"},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "敗北の静けさ", "en": "the stillness of defeat", **_P},
        {"jp": "敗北の静けさが", "en": "the stillness of defeat", **_P},
        {"jp": "体育館", "reading": "たいいくかん", "en": "gymnasium"},
        {"jp": "満たす", "reading": "みたす", "en": "to fill"},
        {"jp": "満たしていた", "en": "filled", **_P},
        {"jp": "体育館を満たしていた", "en": "filled the gymnasium", **_P},
        {"jp": "敗北の静けさが　体育館を満たしていた", "en": "…and the stillness of defeat filled the gymnasium", **_P},
    ],
    "ten_thousand": [
        {"jp": "万", "reading": "まん", "en": "ten thousand"},
        {"jp": "一万", "reading": "いちまん", "en": "ten thousand"},
        {"jp": "鶴", "reading": "つる", "en": "crane"},
        {"jp": "一万の鶴", "en": "ten thousand cranes", **_P},
        {"jp": "一万の鶴も", "en": "even ten thousand cranes", **_P},
        {"jp": "始まり", "reading": "はじまり", "en": "beginning"},
        {"jp": "始まりは", "en": "began with", **_P},
        {"jp": "一枚", "reading": "いちまい", "en": "a single (sheet)"},
        {"jp": "紙", "reading": "かみ", "en": "paper / sheet"},
        {"jp": "一枚の紙", "en": "a single sheet of paper", **_P},
        {"jp": "一枚の紙だった", "en": "a single sheet of paper", **_P},
        {"jp": "始まりは一枚の紙だった", "en": "began with a single sheet of paper", **_P},
        {"jp": "一万の鶴も、　始まりは一枚の紙だった", "en": "Even ten thousand cranes began with a single sheet of paper", **_P},
    ],
    "phrase": [
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "壇上", "reading": "だんじょう", "en": "stage"},
        {"jp": "静かな壇上", "en": "the quiet stage", **_P},
        {"jp": "静かな壇上で", "en": "upon the quiet stage", **_P},
        {"jp": "一つ", "reading": "ひとつ", "en": "a single / one"},
        {"jp": "言葉", "reading": "ことば", "en": "word"},
        {"jp": "一つの言葉", "en": "a single word", **_P},
        {"jp": "放つ", "reading": "ほうつ", "en": "to speak / release"},
        {"jp": "放たれ", "en": "was spoken", **_P},
        {"jp": "一つの言葉が放たれ", "en": "a single word was spoken", **_P},
        {"jp": "静かな壇上で　一つの言葉が放たれ", "en": "Upon the quiet stage a single word was spoken", **_P},
        {"jp": "句", "reading": "く", "en": "phrase / verse line"},
        {"jp": "短い", "reading": "みじかい", "en": "brief / short"},
        {"jp": "短い句", "en": "a brief phrase", **_P},
        {"jp": "短い句が", "en": "a brief phrase", **_P},
        {"jp": "人々", "reading": "ひとびと", "en": "people"},
        {"jp": "胸", "reading": "むね", "en": "hearts / chest"},
        {"jp": "人々の胸", "en": "people's hearts", **_P},
        {"jp": "落ちてゆく", "en": "fell into", **_P},
        {"jp": "人々の胸へ落ちてゆく", "en": "fell into people's hearts", **_P},
        {"jp": "短い句が　人々の胸へ落ちてゆく", "en": "…and a brief phrase fell into people's hearts", **_P},
    ],
    "texture": [
        {"jp": "柔らか", "reading": "やわらか", "en": "soft"},
        {"jp": "布", "reading": "ぬの", "en": "cloth"},
        {"jp": "柔らかな布", "en": "the soft cloth", **_P},
        {"jp": "柔らかな布に", "en": "the soft cloth", **_P},
        {"jp": "そっと", "reading": "そっと", "en": "gently"},
        {"jp": "触れる", "reading": "ふれる", "en": "to touch"},
        {"jp": "触れれば", "en": "touching", **_P},
        {"jp": "そっと触れれば", "en": "touching gently", **_P},
        {"jp": "柔らかな布に　そっと触れれば", "en": "Touching the soft cloth gently", **_P},
        {"jp": "質", "reading": "しつ", "en": "quality / texture"},
        {"jp": "目", "reading": "め", "en": "eye"},
        {"jp": "見える", "reading": "みえる", "en": "to see / be visible"},
        {"jp": "見えぬ", "en": "unseen", **_P},
        {"jp": "目には見えぬ", "en": "unseen to the eye", **_P},
        {"jp": "温もり", "reading": "ぬくもり", "en": "warmth"},
        {"jp": "目には見えぬ温もり", "en": "an unseen warmth", **_P},
        {"jp": "目には見えぬ温もりが", "en": "an unseen warmth", **_P},
        {"jp": "指先", "reading": "ゆびさき", "en": "fingertips"},
        {"jp": "残る", "reading": "のこる", "en": "to remain / linger"},
        {"jp": "残った", "en": "remained", **_P},
        {"jp": "指先に残った", "en": "remained upon the fingertips", **_P},
        {"jp": "目には見えぬ温もりが　指先に残った", "en": "…an unseen warmth remained upon the fingertips", **_P},
    ],
    "ten_days": [
        {"jp": "十日", "reading": "じゅっにち", "en": "ten days"},
        {"jp": "ごと", "reading": "ごと", "en": "every / each"},
        {"jp": "十日ごとに", "en": "every ten days", **_P},
        {"jp": "風", "reading": "かぜ", "en": "wind"},
        {"jp": "匂い", "reading": "におい", "en": "scent"},
        {"jp": "風の匂い", "en": "the scent of the wind", **_P},
        {"jp": "風の匂いが", "en": "the scent of the wind", **_P},
        {"jp": "変わる", "reading": "かわる", "en": "to change"},
        {"jp": "変わり", "en": "would change", **_P},
        {"jp": "風の匂いが変わり", "en": "the scent of the wind would change", **_P},
        {"jp": "十日ごとに　風の匂いが変わり", "en": "Every ten days the scent of the wind would change", **_P},
        {"jp": "旬", "reading": "じゅん", "en": "ten-day period / season"},
        {"jp": "季節", "reading": "きせつ", "en": "season"},
        {"jp": "季節は", "en": "the season", **_P},
        {"jp": "ゆっくり", "reading": "ゆっくり", "en": "slowly"},
        {"jp": "ゆっくりと", "en": "slowly", **_P},
        {"jp": "季節はゆっくりと", "en": "the season slowly", **_P},
        {"jp": "次", "reading": "つぎ", "en": "next"},
        {"jp": "進む", "reading": "すすむ", "en": "to move on / advance"},
        {"jp": "進んでいた", "en": "was moving on", **_P},
        {"jp": "次へ進んでいた", "en": "moved on", **_P},
        {"jp": "季節はゆっくりと　次へ進んでいた", "en": "…and the season slowly moved on", **_P},
    ],
    "ladle": [
        {"jp": "紫", "reading": "むらさき", "en": "purple"},
        {"jp": "鍋", "reading": "なべ", "en": "pot"},
        {"jp": "紫の鍋", "en": "the purple pot", **_P},
        {"jp": "紫の鍋から", "en": "from the purple pot", **_P},
        {"jp": "湯気", "reading": "ゆげ", "en": "steam"},
        {"jp": "立ちのぼる", "reading": "たちのぼる", "en": "to rise up"},
        {"jp": "立ちのぼり", "en": "rose up", **_P},
        {"jp": "湯気が立ちのぼり", "en": "steam rose up", **_P},
        {"jp": "紫の鍋から　湯気が立ちのぼり", "en": "Steam rose from the purple pot", **_P},
        {"jp": "斗", "reading": "と", "en": "ladle (measure)"},
        {"jp": "怪光", "reading": "かいこう", "en": "strange light"},
        {"jp": "怪光が", "en": "a strange light", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "揺れる", "reading": "ゆれる", "en": "to flicker / sway"},
        {"jp": "揺れていた", "en": "was flickering", **_P},
        {"jp": "静かに揺れていた", "en": "was quietly flickering", **_P},
        {"jp": "怪光が　静かに揺れていた", "en": "…and a strange light was quietly flickering", **_P},
    ],
    "bulls_eye": [
        {"jp": "弓", "reading": "ゆみ", "en": "bow"},
        {"jp": "引く", "reading": "ひく", "en": "to draw (a bow)"},
        {"jp": "弓を引く", "en": "the drawn bow", **_P},
        {"jp": "音", "reading": "おと", "en": "sound"},
        {"jp": "弓を引く音", "en": "the sound of the drawn bow", **_P},
        {"jp": "弓を引く音の", "en": "beyond the sound of the drawn bow", **_P},
        {"jp": "向こう", "reading": "むこう", "en": "beyond"},
        {"jp": "向こうで", "en": "beyond", **_P},
        {"jp": "弓を引く音の　向こうで", "en": "Beyond the sound of the drawn bow", **_P},
        {"jp": "的", "reading": "まと", "en": "target / bull's-eye"},
        {"jp": "一点", "reading": "いってん", "en": "a point"},
        {"jp": "静寂", "reading": "せいじゃく", "en": "silence / stillness"},
        {"jp": "一点の静寂", "en": "a point of silence", **_P},
        {"jp": "一点の静寂だけ", "en": "only a point of silence", **_P},
        {"jp": "一点の静寂だけが", "en": "only a point of silence", **_P},
        {"jp": "見つめる", "reading": "みつめる", "en": "to fix upon / gaze at"},
        {"jp": "見つめていた", "en": "was fixed upon", **_P},
        {"jp": "的を見つめていた", "en": "was fixed upon the target", **_P},
        {"jp": "一点の静寂だけが　的を見つめていた", "en": "…only a point of silence was fixed upon the target", **_P},
    ],
    "neck": [
        {"jp": "巻く", "reading": "まく", "en": "to wrap"},
        {"jp": "巻かれた", "en": "wrapped", **_P},
        {"jp": "マフラー", "reading": "マフラー", "en": "scarf"},
        {"jp": "巻かれたマフラー", "en": "a wrapped scarf", **_P},
        {"jp": "巻かれたマフラーの", "en": "of a wrapped scarf", **_P},
        {"jp": "ぬくもり", "reading": "ぬくもり", "en": "warmth"},
        {"jp": "巻かれたマフラーの　ぬくもりに", "en": "in the warmth of a wrapped scarf", **_P},
        {"jp": "頸", "reading": "くび", "en": "neck"},
        {"jp": "言葉", "reading": "ことば", "en": "words"},
        {"jp": "より", "reading": "より", "en": "than"},
        {"jp": "言葉より", "en": "than words", **_P},
        {"jp": "深い", "reading": "ふかい", "en": "deep / deeper"},
        {"jp": "想い", "reading": "おもい", "en": "feeling"},
        {"jp": "言葉より深い想い", "en": "a feeling deeper than words", **_P},
        {"jp": "言葉より深い想いが", "en": "a feeling deeper than words", **_P},
        {"jp": "そっと", "reading": "そっと", "en": "gently"},
        {"jp": "触れる", "reading": "ふれる", "en": "to touch"},
        {"jp": "触れていた", "en": "was touching", **_P},
        {"jp": "そっと触れていた", "en": "was gently touching", **_P},
        {"jp": "言葉より深い想いが　そっと触れていた", "en": "…a feeling deeper than words was gently touching", **_P},
    ],
    "hook": [
        {"jp": "小さな", "reading": "ちいさな", "en": "small"},
        {"jp": "鉤", "reading": "かぎ", "en": "hook"},
        {"jp": "小さな鉤", "en": "a small hook", **_P},
        {"jp": "小さな鉤に", "en": "from a small hook", **_P},
        {"jp": "鞄", "reading": "かばん", "en": "bag"},
        {"jp": "揺れる", "reading": "ゆれる", "en": "to sway"},
        {"jp": "揺れ", "en": "swayed", **_P},
        {"jp": "鞄が揺れ", "en": "a bag swayed", **_P},
        {"jp": "小さな鉤に　鞄が揺れ", "en": "A bag swayed from a small hook", **_P},
        {"jp": "帰り", "reading": "かえり", "en": "return / homecoming"},
        {"jp": "待つ", "reading": "まつ", "en": "to wait for"},
        {"jp": "帰りを待つ", "en": "waiting for someone's return", **_P},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "帰りを待つ部屋", "en": "the room waiting for someone's return", **_P},
        {"jp": "帰りを待つ部屋が", "en": "the room waiting for someone's return", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "息づく", "reading": "いきづく", "en": "to breathe / come alive"},
        {"jp": "息づいていた", "en": "was quietly breathing", **_P},
        {"jp": "静かに息づいていた", "en": "was quietly breathing", **_P},
        {"jp": "帰りを待つ部屋が　静かに息づいていた", "en": "…and the room waiting for someone's return was quietly breathing", **_P},
    ],
    "riot": [
        {"jp": "燃える", "reading": "もえる", "en": "burning"},
        {"jp": "街角", "reading": "まちかど", "en": "street corner"},
        {"jp": "燃える街角", "en": "the burning street corner", **_P},
        {"jp": "燃える街角に", "en": "at the burning street corner", **_P},
        {"jp": "怒号", "reading": "どごう", "en": "shouts / angry roars"},
        {"jp": "響く", "reading": "ひびく", "en": "to ring out / echo"},
        {"jp": "響き", "en": "rang out", **_P},
        {"jp": "怒号が響き", "en": "shouts rang out", **_P},
        {"jp": "燃える街角に　怒号が響き", "en": "At the burning street corner shouts rang out", **_P},
        {"jp": "乱", "reading": "らん", "en": "riot / disorder"},
        {"jp": "秩序", "reading": "ちつじょ", "en": "order"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "秩序の光", "en": "the light of order", **_P},
        {"jp": "秩序の光が", "en": "the light of order", **_P},
        {"jp": "夜", "reading": "よる", "en": "night"},
        {"jp": "崩れる", "reading": "くずれる", "en": "to crumble / collapse"},
        {"jp": "崩れていった", "en": "crumbled into", **_P},
        {"jp": "夜へ崩れていった", "en": "crumbled into the night", **_P},
        {"jp": "秩序の光が　夜へ崩れていった", "en": "…and the light of order crumbled into the night", **_P},
    ],
    "straightaway": [
        {"jp": "闇", "reading": "やみ", "en": "darkness"},
        {"jp": "奥", "reading": "おく", "en": "depths / heart"},
        {"jp": "闇の奥", "en": "the depths of darkness", **_P},
        {"jp": "闇の奥へ", "en": "into the depths of darkness", **_P},
        {"jp": "一本", "reading": "いっぽん", "en": "a single"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "一本の光", "en": "a single light", **_P},
        {"jp": "闇の奥へ　一本の光", "en": "Into the depths of darkness a single light", **_P},
        {"jp": "直", "reading": "ちょく", "en": "straight / direct"},
        {"jp": "迷い", "reading": "まよい", "en": "hesitation / wandering"},
        {"jp": "迷いのない", "en": "unwavering", **_P},
        {"jp": "道", "reading": "みち", "en": "path / way"},
        {"jp": "迷いのない道", "en": "an unwavering path", **_P},
        {"jp": "迷いのない道が", "en": "an unwavering path", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "続く", "reading": "つづく", "en": "to continue"},
        {"jp": "続いていた", "en": "continued", **_P},
        {"jp": "静かに続いていた", "en": "quietly continued", **_P},
        {"jp": "迷いのない道が　静かに続いていた", "en": "…an unwavering path quietly continued", **_P},
    ],
    "tool": [
        {"jp": "黒い", "reading": "くろい", "en": "black"},
        {"jp": "机", "reading": "つくえ", "en": "desk"},
        {"jp": "黒い机", "en": "the black desk", **_P},
        {"jp": "黒い机に", "en": "on the black desk", **_P},
        {"jp": "道具", "reading": "どうぐ", "en": "tools"},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to line up"},
        {"jp": "並び", "en": "lined up", **_P},
        {"jp": "道具が並び", "en": "tools lined up", **_P},
        {"jp": "黒い机に　道具が並び", "en": "Tools lined up on the black desk", **_P},
        {"jp": "具", "reading": "ぐ", "en": "tool / implement"},
        {"jp": "使い込む", "reading": "つかいこむ", "en": "well-worn / broken in"},
        {"jp": "使い込まれた", "en": "well-worn", **_P},
        {"jp": "手", "reading": "て", "en": "hands"},
        {"jp": "使い込まれた手", "en": "well-worn hands", **_P},
        {"jp": "使い込まれた手の", "en": "of well-worn hands", **_P},
        {"jp": "記憶", "reading": "きおく", "en": "memory"},
        {"jp": "使い込まれた手の　記憶", "en": "the memory of well-worn hands", **_P},
        {"jp": "記憶が", "en": "the memory", **_P},
        {"jp": "そこ", "reading": "そこ", "en": "there"},
        {"jp": "残る", "reading": "のこる", "en": "to remain / linger"},
        {"jp": "残っていた", "en": "remained", **_P},
        {"jp": "そこに残っていた", "en": "remained there", **_P},
        {"jp": "使い込まれた手の　記憶が　そこに残っていた", "en": "…and the memory of well-worn hands remained there", **_P},
    ],
    "true": [
        {"jp": "深い", "reading": "ふかい", "en": "deep"},
        {"jp": "闇", "reading": "やみ", "en": "darkness"},
        {"jp": "深い闇", "en": "deep darkness", **_P},
        {"jp": "中心", "reading": "ちゅうしん", "en": "heart / center"},
        {"jp": "深い闇の中心", "en": "the heart of deep darkness", **_P},
        {"jp": "深い闇の中心に", "en": "at the heart of deep darkness", **_P},
        {"jp": "小さな", "reading": "ちいさな", "en": "small"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "小さな光", "en": "a small light", **_P},
        {"jp": "深い闇の中心に　小さな光", "en": "At the heart of deep darkness a small light", **_P},
        {"jp": "真", "reading": "しん", "en": "true / genuine"},
        {"jp": "真実", "reading": "しんじつ", "en": "truth"},
        {"jp": "真実だけ", "en": "only truth", **_P},
        {"jp": "真実だけが", "en": "only truth", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "燃える", "reading": "もえる", "en": "to burn"},
        {"jp": "燃えていた", "en": "was burning", **_P},
        {"jp": "静かに燃えていた", "en": "was quietly burning", **_P},
        {"jp": "真実だけが　静かに燃えていた", "en": "…only truth was quietly burning", **_P},
    ],
}
