"""Hand-curated vocabulary → phrase sequences for Lesson 2 Vocabulary Exhibition.

Kanji and content words are introduced individually; grammar folds into phrases.
If a word was already taught in this sequence, it reappears only inside a larger phrase.
"""

from __future__ import annotations

_P = {"phrase": True}

VOCABULARY_BY_SLUG: dict[str, list[dict]] = {
    "prosperous": [
        {"jp": "湖面", "reading": "みなも", "en": "the lake's surface"},
        {"jp": "湖面に", "en": "upon the lake's surface", **_P},
        {"jp": "二", "reading": "ふた", "en": "two"},
        {"jp": "日", "reading": "ひ", "en": "sun"},
        {"jp": "二つの日", "en": "two suns", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to line up / rest side by side"},
        {"jp": "並び", "reading": "ならび", "en": "resting side by side", **_P},
        {"jp": "静かに並び", "en": "rested quietly", **_P},
        {"jp": "二つの日が静かに並び", "en": "two suns rested quietly", **_P},
        {"jp": "湖面に　二つの日が静かに並び", "en": "Two suns rested quietly upon the lake", **_P},
        {"jp": "昌", "reading": "しょう", "en": "prosperous / thriving"},
        {"jp": "霧", "reading": "きり", "en": "mist"},
        {"jp": "谷", "reading": "たに", "en": "valley"},
        {"jp": "霧の谷", "en": "the misty valley", **_P},
        {"jp": "霧の谷だけ", "en": "only the misty valley", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "留める", "reading": "とめる", "en": "to hold / keep"},
        {"jp": "光を留めていた", "en": "held their light", **_P},
        {"jp": "霧の谷だけが　光を留めていた", "en": "…while only the misty valley held their light", **_P},
    ],
    "chant": [
        {"jp": "夕暮れ", "reading": "ゆうぐれ", "en": "dusk / twilight"},
        {"jp": "鐘楼", "reading": "しょうろう", "en": "belfry"},
        {"jp": "夕暮れの鐘楼", "en": "the belfry at dusk", **_P},
        {"jp": "夕暮れの鐘楼に", "en": "in the belfry at dusk", **_P},
        {"jp": "釣り鐘", "reading": "つりがね", "en": "hanging temple bell"},
        {"jp": "吊る", "reading": "つる", "en": "to hang"},
        {"jp": "釣り鐘が吊る", "en": "the temple bell hung still", **_P},
        {"jp": "夕暮れの鐘楼に　釣り鐘が吊る", "en": "In the belfry at dusk the temple bell hung still", **_P},
        {"jp": "唱", "reading": "しょう", "en": "to chant / recite"},
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "静かな光", "en": "quiet light", **_P},
        {"jp": "静かな光だけ", "en": "only the quiet light", **_P},
        {"jp": "声", "reading": "こえ", "en": "voice"},
        {"jp": "包む", "reading": "つつむ", "en": "to wrap / enfold"},
        {"jp": "声を包んでいた", "en": "wrapped around its voice", **_P},
        {"jp": "静かな光だけが　声を包んでいた", "en": "…while only the quiet light wrapped around its voice", **_P},
    ],
    "sparkle": [
        {"jp": "三", "reading": "みっ", "en": "three"},
        {"jp": "三つ", "en": "three", **_P},
        {"jp": "水", "reading": "みず", "en": "water"},
        {"jp": "晶", "reading": "しょう", "en": "crystal / sparkle"},
        {"jp": "水晶", "reading": "すいしょう", "en": "crystal", **_P},
        {"jp": "三つの水晶", "en": "three crystals", **_P},
        {"jp": "机", "reading": "つくえ", "en": "desk / table"},
        {"jp": "上", "reading": "うえ", "en": "upon / top"},
        {"jp": "机の上", "en": "upon the table", **_P},
        {"jp": "机の上に", "en": "upon the wooden table", **_P},
        {"jp": "置かれる", "reading": "おかれる", "en": "to be placed"},
        {"jp": "置かれ", "en": "rested", **_P},
        {"jp": "三つの水晶が　机の上に置かれ", "en": "Three crystals rested upon the wooden table", **_P},
        {"jp": "棱", "reading": "りょう", "en": "facet / edge"},
        {"jp": "棱の光", "en": "their faceted light", **_P},
        {"jp": "棱の光だけ", "en": "only their faceted light", **_P},
        {"jp": "森", "reading": "もり", "en": "forest"},
        {"jp": "溢れる", "reading": "あふれる", "en": "to spill / overflow"},
        {"jp": "森へ溢れていた", "en": "spilled toward the forest", **_P},
        {"jp": "棱の光だけが　森へ溢れていた", "en": "…while only their faceted light spilled toward the forest", **_P},
    ],
    "goods": [
        {"jp": "三", "reading": "みっ", "en": "three"},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "三つの碗", "en": "three bowls", **_P},
        {"jp": "重ねる", "reading": "かさねる", "en": "to stack"},
        {"jp": "重ねて", "en": "stacked", **_P},
        {"jp": "置かれる", "reading": "おかれる", "en": "to be placed"},
        {"jp": "置かれ", "en": "were placed", **_P},
        {"jp": "重ねて置かれ", "en": "were stacked upon the table", **_P},
        {"jp": "三つの碗が　重ねて置かれ", "en": "Three bowls were stacked upon the table", **_P},
        {"jp": "品", "reading": "ひん", "en": "goods / article"},
        {"jp": "障子", "reading": "しょうじ", "en": "shoji (paper screen door)"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "障子の光", "en": "light through the shoji", **_P},
        {"jp": "障子の光だけ", "en": "only the shoji light", **_P},
        {"jp": "金", "reading": "きん", "en": "metal"},
        {"jp": "温める", "reading": "あたためる", "en": "to warm"},
        {"jp": "金を温めていた", "en": "warmed their metal", **_P},
        {"jp": "障子の光だけが　金を温めていた", "en": "…while only the shoji light warmed their metal", **_P},
    ],
    "spine": [
        {"jp": "二", "reading": "ふた", "en": "two"},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "二つの碗", "en": "two bowls", **_P},
        {"jp": "空", "reading": "くう", "en": "sky / air"},
        {"jp": "中", "reading": "ちゅう", "en": "middle / within"},
        {"jp": "空中", "reading": "くうちゅう", "en": "midair", **_P},
        {"jp": "空中に", "en": "in midair", **_P},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to align / line up"},
        {"jp": "並び", "reading": "ならび", "en": "aligned", **_P},
        {"jp": "二つの碗が　空中に並び", "en": "Two bowls aligned in midair one above the other", **_P},
        {"jp": "呂", "reading": "ろ", "en": "spine / backbone"},
        {"jp": "縦", "reading": "たて", "en": "vertical"},
        {"jp": "隙間", "reading": "すきま", "en": "gap / space between"},
        {"jp": "縦の隙間", "en": "the vertical gap", **_P},
        {"jp": "縦の隙間だけ", "en": "only the vertical gap", **_P},
        {"jp": "姿", "reading": "すがた", "en": "form / figure"},
        {"jp": "支える", "reading": "ささえる", "en": "to support / hold up"},
        {"jp": "姿を支えていた", "en": "held their form", **_P},
        {"jp": "縦の隙間だけが　姿を支えていた", "en": "…while only the vertical gap between them held their form", **_P},
    ],
    "early": [
        {"jp": "朝", "reading": "あさ", "en": "morning"},
        {"jp": "平原", "reading": "へいげん", "en": "open plain"},
        {"jp": "朝の平原", "en": "the morning plain", **_P},
        {"jp": "朝の平原に", "en": "upon the morning plain", **_P},
        {"jp": "一本", "reading": "いっぽん", "en": "one (post)"},
        {"jp": "柱", "reading": "はしら", "en": "post / pillar"},
        {"jp": "一本の柱", "en": "a single post", **_P},
        {"jp": "立つ", "reading": "たつ", "en": "to stand"},
        {"jp": "立ち", "en": "stood tall", **_P},
        {"jp": "一本の柱が立ち", "en": "a single post stood tall", **_P},
        {"jp": "朝の平原に　一本の柱が立ち", "en": "Upon the morning plain a single post stood tall", **_P},
        {"jp": "早", "reading": "そう", "en": "early"},
        {"jp": "水", "reading": "みず", "en": "water"},
        {"jp": "十字", "reading": "じゅうじ", "en": "cross"},
        {"jp": "水の十字", "en": "the cross of water", **_P},
        {"jp": "水の十字だけ", "en": "only the cross of water", **_P},
        {"jp": "一日", "reading": "いちにち", "en": "the day"},
        {"jp": "告げる", "reading": "つげる", "en": "to herald"},
        {"jp": "一日を告げていた", "en": "heralded the day", **_P},
        {"jp": "水の十字だけが　一日を告げていた", "en": "…while only the cross of water heralded the day", **_P},
    ],
    "rising_sun": [
        {"jp": "山", "reading": "やま", "en": "mountain"},
        {"jp": "端", "reading": "は", "en": "edge"},
        {"jp": "山の端", "en": "the mountain's edge", **_P},
        {"jp": "山の端から", "en": "from behind the mountain's edge", **_P},
        {"jp": "旭", "reading": "きょく", "en": "rising sun"},
        {"jp": "朝日", "reading": "あさひ", "en": "morning sun"},
        {"jp": "顔", "reading": "かお", "en": "face"},
        {"jp": "出す", "reading": "だす", "en": "to show / emerge"},
        {"jp": "顔を出し", "en": "showed its face", **_P},
        {"jp": "朝日が顔を出し", "en": "the morning sun showed its face", **_P},
        {"jp": "山の端から　朝日が顔を出し", "en": "From behind the mountain's edge the sun appeared", **_P},
        {"jp": "池", "reading": "いけ", "en": "pond"},
        {"jp": "柱", "reading": "はしら", "en": "post"},
        {"jp": "池の柱", "en": "the post in the pond", **_P},
        {"jp": "池の柱だけ", "en": "only the post in the pond", **_P},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "留める", "reading": "とめる", "en": "to keep / hold"},
        {"jp": "影を留めていた", "en": "kept its shadow", **_P},
        {"jp": "池の柱だけが　影を留めていた", "en": "…while only the post in the pond kept its shadow", **_P},
    ],
    "generation": [
        {"jp": "幾", "reading": "いく", "en": "several / many"},
        {"jp": "世", "reading": "よ", "en": "generation / world"},
        {"jp": "代", "reading": "だい", "en": "generation / era"},
        {"jp": "幾世代", "reading": "いくせだい", "en": "countless generations", **_P},
        {"jp": "幾世代も", "en": "for countless generations", **_P},
        {"jp": "同じ", "reading": "おなじ", "en": "same"},
        {"jp": "湖", "reading": "みずうみ", "en": "lake"},
        {"jp": "照らす", "reading": "てらす", "en": "to illuminate / light"},
        {"jp": "同じ湖を照らし", "en": "the same lake was lit", **_P},
        {"jp": "幾世代も　同じ湖を照らし", "en": "For countless generations the same lake was lit", **_P},
        {"jp": "黄金", "reading": "おうごん", "en": "gold / golden"},
        {"jp": "霧", "reading": "きり", "en": "mist"},
        {"jp": "黄金の霧", "en": "the golden mist", **_P},
        {"jp": "黄金の霧だけ", "en": "only the golden mist", **_P},
        {"jp": "岸", "reading": "きし", "en": "shoreline"},
        {"jp": "包む", "reading": "つつむ", "en": "to wrap"},
        {"jp": "岸を包んでいた", "en": "wrapped the shoreline", **_P},
        {"jp": "黄金の霧だけが　岸を包んでいた", "en": "…while only the golden mist wrapped the shoreline", **_P},
    ],
    "stomach": [
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "静かな部屋", "en": "the quiet room", **_P},
        {"jp": "静かな部屋に", "en": "in the quiet room", **_P},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "溢れる", "reading": "あふれる", "en": "to overflow"},
        {"jp": "碗から光が溢れ", "en": "light overflowed from the bowl", **_P},
        {"jp": "静かな部屋に　碗から光が溢れ", "en": "In the quiet room light overflowed from the bowl", **_P},
        {"jp": "胃", "reading": "い", "en": "stomach"},
        {"jp": "夕", "reading": "ゆう", "en": "evening"},
        {"jp": "山", "reading": "やま", "en": "mountain"},
        {"jp": "夕の山", "en": "the evening mountains", **_P},
        {"jp": "夕の山だけ", "en": "only the evening mountains", **_P},
        {"jp": "窓", "reading": "まど", "en": "window"},
        {"jp": "外", "reading": "そと", "en": "outside / beyond"},
        {"jp": "続く", "reading": "つづく", "en": "to continue"},
        {"jp": "窓の外に続いた", "en": "continued beyond the window", **_P},
        {"jp": "夕の山だけが　窓の外に続いた", "en": "…while only the evening mountains continued beyond the window", **_P},
    ],
    "dawn": [
        {"jp": "水平線", "reading": "すいへいせん", "en": "horizon"},
        {"jp": "水平線から", "en": "from the horizon", **_P},
        {"jp": "旦", "reading": "たん", "en": "dawn"},
        {"jp": "朝日", "reading": "あさひ", "en": "morning sun"},
        {"jp": "顔", "reading": "かお", "en": "face"},
        {"jp": "出す", "reading": "だす", "en": "to show / emerge"},
        {"jp": "顔を出し", "en": "showed its face", **_P},
        {"jp": "朝日が顔を出し", "en": "the morning sun showed its face", **_P},
        {"jp": "水平線から　朝日が顔を出し", "en": "From the horizon the morning sun showed its face", **_P},
        {"jp": "空", "reading": "そら", "en": "sky"},
        {"jp": "余白", "reading": "よはく", "en": "open space / blank margin"},
        {"jp": "空の余白", "en": "the open sky", **_P},
        {"jp": "空の余白だけ", "en": "only the open sky", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "迎える", "reading": "むかえる", "en": "to welcome / receive"},
        {"jp": "光を迎えていた", "en": "welcomed the light", **_P},
        {"jp": "空の余白だけが　光を迎えていた", "en": "…while only the open sky welcomed the light", **_P},
    ],
    "gallbladder": [
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "上", "reading": "うえ", "en": "above / upon"},
        {"jp": "碗の上", "en": "above the bowl", **_P},
        {"jp": "碗の上に", "en": "above the bowl", **_P},
        {"jp": "一滴", "reading": "いってき", "en": "a single drop"},
        {"jp": "静止", "reading": "せいし", "en": "motionless / stillness"},
        {"jp": "静止し", "en": "hung motionless", **_P},
        {"jp": "一滴が静止し", "en": "a single drop hung motionless", **_P},
        {"jp": "碗の上に　一滴が静止し", "en": "Above the bowl a single drop hung motionless", **_P},
        {"jp": "胆", "reading": "たん", "en": "gallbladder / courage"},
        {"jp": "黄金", "reading": "おうごん", "en": "golden"},
        {"jp": "黄金の光", "en": "golden light", **_P},
        {"jp": "黄金の光だけ", "en": "only its golden light", **_P},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "満たす", "reading": "みたす", "en": "to fill"},
        {"jp": "部屋を満たしていた", "en": "filled the room", **_P},
        {"jp": "黄金の光だけが　部屋を満たしていた", "en": "…while only its golden light filled the room", **_P},
    ],
    "span": [
        {"jp": "夕", "reading": "ゆう", "en": "evening"},
        {"jp": "谷底", "reading": "たにぞこ", "en": "valley floor"},
        {"jp": "夕の谷底", "en": "the evening valley", **_P},
        {"jp": "夕の谷底に", "en": "through the evening valley", **_P},
        {"jp": "亘", "reading": "わたる", "en": "to span / extend across"},
        {"jp": "川", "reading": "かわ", "en": "river"},
        {"jp": "曲がる", "reading": "まがる", "en": "to curve / bend"},
        {"jp": "大きく曲がり", "en": "curved wide", **_P},
        {"jp": "川が大きく曲がり", "en": "the river curved wide", **_P},
        {"jp": "夕の谷底に　川が大きく曲がり", "en": "Through the evening valley the river curved wide", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "帯", "reading": "おび", "en": "band / strip"},
        {"jp": "光の帯", "en": "the band of light", **_P},
        {"jp": "光の帯だけ", "en": "only the band of light", **_P},
        {"jp": "越える", "reading": "こえる", "en": "to cross over"},
        {"jp": "続く", "reading": "つづく", "en": "to continue"},
        {"jp": "山を越えて続いた", "en": "continued across the mountains", **_P},
        {"jp": "光の帯だけが　山を越えて続いた", "en": "…while only the band of light continued across the mountains", **_P},
    ],
    "concave": [
        {"jp": "三日月", "reading": "みかづき", "en": "crescent moon"},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "三日月の碗", "en": "the crescent bowl", **_P},
        {"jp": "机", "reading": "つくえ", "en": "table"},
        {"jp": "机の上", "en": "upon the table", **_P},
        {"jp": "机の上で", "en": "upon the wooden table", **_P},
        {"jp": "光る", "reading": "ひかる", "en": "to glow"},
        {"jp": "光り", "en": "glowed", **_P},
        {"jp": "三日月の碗が　机の上で光り", "en": "The crescent bowl glowed upon the wooden table", **_P},
        {"jp": "凹", "reading": "おう", "en": "concave / hollow"},
        {"jp": "窓", "reading": "まど", "en": "window"},
        {"jp": "夕景", "reading": "ゆうけ", "en": "sunset view"},
        {"jp": "窓の夕景", "en": "the sunset through the window", **_P},
        {"jp": "窓の夕景だけ", "en": "only the sunset through the window", **_P},
        {"jp": "窪み", "reading": "くぼみ", "en": "hollow / concavity"},
        {"jp": "映す", "reading": "うつす", "en": "to mirror / reflect"},
        {"jp": "窪みを映していた", "en": "mirrored its hollow", **_P},
        {"jp": "窓の夕景だけが　窪みを映していた", "en": "…while only the sunset through the window mirrored its hollow", **_P},
    ],
    "convex": [
        {"jp": "舟", "reading": "ふね", "en": "boat"},
        {"jp": "形", "reading": "がた", "en": "shape / form"},
        {"jp": "舟形", "reading": "ふながた", "en": "boat-shaped", **_P},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "舟形の碗", "en": "the boat-shaped bowl", **_P},
        {"jp": "机", "reading": "つくえ", "en": "table"},
        {"jp": "机の上", "en": "upon the table", **_P},
        {"jp": "机の上で", "en": "upon the table", **_P},
        {"jp": "膨らむ", "reading": "ふくらむ", "en": "to swell / bulge"},
        {"jp": "膨らみ", "en": "swelled", **_P},
        {"jp": "舟形の碗が　机の上で膨らみ", "en": "The boat-shaped bowl swelled upon the table", **_P},
        {"jp": "凸", "reading": "とつ", "en": "convex / bulging"},
        {"jp": "内側", "reading": "うちがわ", "en": "inner side / within"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "内側の光", "en": "the light within", **_P},
        {"jp": "内側の光だけ", "en": "only the light within", **_P},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "押し上げる", "reading": "おしあげる", "en": "to push upward"},
        {"jp": "影を押し上げた", "en": "pushed the shadow upward", **_P},
        {"jp": "内側の光だけが　影を押し上げた", "en": "…while only the light within pushed the shadow upward", **_P},
    ],
    "olden_times": [
        {"jp": "古い", "reading": "ふるい", "en": "old / aged"},
        {"jp": "窓辺", "reading": "まどべ", "en": "window ledge"},
        {"jp": "古い窓辺", "en": "the aged window", **_P},
        {"jp": "古い窓辺に", "en": "through the aged window", **_P},
        {"jp": "夕日", "reading": "ゆうひ", "en": "setting sun / sunset light"},
        {"jp": "差し込む", "reading": "さしこむ", "en": "to stream in"},
        {"jp": "差し込み", "en": "streamed in", **_P},
        {"jp": "夕日が差し込み", "en": "sunset light streamed in", **_P},
        {"jp": "古い窓辺に　夕日が差し込み", "en": "Sunset light streamed through the aged window", **_P},
        {"jp": "旧", "reading": "きゅう", "en": "olden / former times"},
        {"jp": "削れる", "reading": "けずれる", "en": "to wear away"},
        {"jp": "削れた", "en": "worn", **_P},
        {"jp": "壁", "reading": "かべ", "en": "wall"},
        {"jp": "削れた壁", "en": "the worn walls", **_P},
        {"jp": "削れた壁だけ", "en": "only the worn walls", **_P},
        {"jp": "年月", "reading": "としつき", "en": "passing years"},
        {"jp": "留める", "reading": "とめる", "en": "to keep / hold"},
        {"jp": "年月を留めていた", "en": "kept the passing years", **_P},
        {"jp": "削れた壁だけが　年月を留めていた", "en": "…while only the worn walls kept the passing years", **_P},
    ],
    "oneself": [
        {"jp": "窓辺", "reading": "まどべ", "en": "window ledge"},
        {"jp": "台", "reading": "だい", "en": "stand / ledge"},
        {"jp": "窓辺の台", "en": "the ledge by the window", **_P},
        {"jp": "窓辺の台に", "en": "upon the ledge by the window", **_P},
        {"jp": "光る", "reading": "ひかる", "en": "to glow"},
        {"jp": "球", "reading": "たま", "en": "sphere / orb"},
        {"jp": "光る球", "en": "a glowing sphere", **_P},
        {"jp": "置かれる", "reading": "おかれる", "en": "to be placed"},
        {"jp": "置かれ", "en": "rested", **_P},
        {"jp": "光る球が置かれ", "en": "a glowing sphere rested", **_P},
        {"jp": "窓辺の台に　光る球が置かれ", "en": "Upon the ledge by the window a glowing sphere rested", **_P},
        {"jp": "自", "reading": "じ", "en": "oneself / self"},
        {"jp": "一人", "reading": "ひとり", "en": "one person / alone"},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "一人の静けさ", "en": "a solitary stillness", **_P},
        {"jp": "一人の静けさだけ", "en": "only a solitary stillness", **_P},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "在る", "reading": "ある", "en": "to be / exist / remain"},
        {"jp": "部屋に在った", "en": "remained in the room", **_P},
        {"jp": "一人の静けさだけが　部屋に在った", "en": "…and only a solitary stillness remained in the room", **_P},
    ],
    "white": [
        {"jp": "白", "reading": "しろ", "en": "white"},
        {"jp": "白い", "en": "white", **_P},
        {"jp": "花", "reading": "はな", "en": "flower"},
        {"jp": "束", "reading": "たば", "en": "bundle / bouquet"},
        {"jp": "花束", "reading": "はなたば", "en": "bouquet", **_P},
        {"jp": "白い花束", "en": "a bouquet of white flowers", **_P},
        {"jp": "窓辺", "reading": "まどべ", "en": "window ledge"},
        {"jp": "窓辺に", "en": "by the window", **_P},
        {"jp": "置かれ", "en": "rested", **_P},
        {"jp": "白い花束が　窓辺に置かれ", "en": "A bouquet of white flowers rested by the window", **_P},
        {"jp": "夕焼け", "reading": "ゆうやけ", "en": "sunset glow"},
        {"jp": "夕焼けだけ", "en": "only the sunset", **_P},
        {"jp": "花びら", "reading": "はなびら", "en": "petal"},
        {"jp": "染める", "reading": "そめる", "en": "to stain / dye"},
        {"jp": "花びらを染めていた", "en": "stained the petals", **_P},
        {"jp": "夕焼けだけが　花びらを染めていた", "en": "…while only the sunset stained the petals", **_P},
    ],
    "hundred": [
        {"jp": "折り紙", "reading": "おりがみ", "en": "origami"},
        {"jp": "鶴", "reading": "つる", "en": "crane"},
        {"jp": "折り紙の鶴", "en": "origami cranes", **_P},
        {"jp": "木", "reading": "き", "en": "wooden"},
        {"jp": "盆", "reading": "ぼん", "en": "tray"},
        {"jp": "木の盆", "en": "the wooden tray", **_P},
        {"jp": "木の盆に", "en": "the wooden tray", **_P},
        {"jp": "溢れる", "reading": "あふれる", "en": "to overflow"},
        {"jp": "溢れ", "en": "overflowed", **_P},
        {"jp": "折り紙の鶴が　木の盆に溢れ", "en": "Origami cranes overflowed the wooden tray", **_P},
        {"jp": "百", "reading": "ひゃく", "en": "hundred"},
        {"jp": "夕", "reading": "ゆう", "en": "evening"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "夕光", "reading": "ゆうこう", "en": "evening light", **_P},
        {"jp": "夕光だけ", "en": "only the evening light", **_P},
        {"jp": "翼", "reading": "つばさ", "en": "wing"},
        {"jp": "百の翼", "en": "a hundred wings", **_P},
        {"jp": "照らす", "reading": "てらす", "en": "to light / illuminate"},
        {"jp": "百の翼を照らした", "en": "lit a hundred wings", **_P},
        {"jp": "夕光だけが　百の翼を照らした", "en": "…while only the evening light lit a hundred wings", **_P},
    ],
    "middle": [
        {"jp": "光る", "reading": "ひかる", "en": "to glow"},
        {"jp": "球", "reading": "たま", "en": "sphere"},
        {"jp": "光る球", "en": "the glowing sphere", **_P},
        {"jp": "中", "reading": "なか", "en": "middle / center"},
        {"jp": "央", "reading": "おう", "en": "center"},
        {"jp": "中央", "reading": "ちゅうおう", "en": "center", **_P},
        {"jp": "光る球の　中央", "en": "the center of the glowing sphere", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "貫く", "reading": "つらぬく", "en": "to pass through"},
        {"jp": "貫き", "en": "passed through", **_P},
        {"jp": "光る球の　中央を光が貫き", "en": "Light passed through the center of the glowing sphere", **_P},
        {"jp": "縦", "reading": "たて", "en": "vertical"},
        {"jp": "筋", "reading": "すじ", "en": "line / streak"},
        {"jp": "縦の筋", "en": "a vertical line", **_P},
        {"jp": "縦の筋だけ", "en": "only a vertical line", **_P},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "留める", "reading": "とめる", "en": "to hold"},
        {"jp": "静けさを留めていた", "en": "held the stillness", **_P},
        {"jp": "縦の筋だけが　静けさを留めていた", "en": "…while only a vertical line held the stillness", **_P},
    ],
    "thousand": [
        {"jp": "廊下", "reading": "ろうか", "en": "corridor"},
        {"jp": "天井", "reading": "てんじょう", "en": "ceiling"},
        {"jp": "廊下の天井", "en": "the corridor ceiling", **_P},
        {"jp": "廊下の天井に", "en": "from the corridor ceiling", **_P},
        {"jp": "千", "reading": "せん", "en": "thousand"},
        {"jp": "鶴", "reading": "つる", "en": "crane"},
        {"jp": "千の鶴", "en": "a thousand cranes", **_P},
        {"jp": "吊る", "reading": "つる", "en": "to hang"},
        {"jp": "千の鶴が吊る", "en": "a thousand cranes hung down", **_P},
        {"jp": "廊下の天井に　千の鶴が吊る", "en": "From the corridor ceiling a thousand cranes hung down", **_P},
        {"jp": "尽きる", "reading": "つきる", "en": "to end / be exhausted"},
        {"jp": "尽きぬ", "reading": "つきぬ", "en": "endless / unceasing", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "尽きぬ光", "en": "endless light", **_P},
        {"jp": "尽きぬ光だけ", "en": "only the endless light", **_P},
        {"jp": "奥", "reading": "おく", "en": "depth / back / interior"},
        {"jp": "続く", "reading": "つづく", "en": "to continue"},
        {"jp": "奥へ続いていた", "en": "continued toward the back", **_P},
        {"jp": "尽きぬ光だけが　奥へ続いていた", "en": "…while only the endless light continued toward the back", **_P},
    ],
}
