"""Hand-curated vocabulary → phrase sequences for Lesson 5 Vocabulary Exhibition.

Kanji and content words are introduced individually; grammar folds into phrases.
If a word was already taught in this sequence, it reappears only inside a larger phrase.
Four-line verses: build lines 1–2, introduce target kanji, then build lines 3–4.
"""

from __future__ import annotations

_P = {"phrase": True}

VOCABULARY_BY_SLUG: dict[str, list[dict]] = {
    "craft": [
        {"jp": "静か", "reading": "しずか", "en": "quiet / silent"},
        {"jp": "静かな", "en": "silent", **_P},
        {"jp": "工房", "reading": "こうぼう", "en": "workshop"},
        {"jp": "静かな工房", "en": "the silent workshop", **_P},
        {"jp": "静かな工房に", "en": "in the silent workshop", **_P},
        {"jp": "刃物", "reading": "はもの", "en": "tools / bladed tools"},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to line up"},
        {"jp": "並び", "en": "lay in order", **_P},
        {"jp": "刃物が並び", "en": "the tools lay in order", **_P},
        {"jp": "静かな工房に　刃物が並び", "en": "In the silent workshop the tools lay in order", **_P},
        {"jp": "工", "reading": "こう", "en": "craft / artisan work"},
        {"jp": "職人", "reading": "しょくにん", "en": "craftsman"},
        {"jp": "息", "reading": "いき", "en": "breath"},
        {"jp": "職人の息", "en": "the craftsman's breath", **_P},
        {"jp": "だけ", "reading": "だけ", "en": "only"},
        {"jp": "職人の息だけが", "en": "only the craftsman's breath", **_P},
        {"jp": "夜", "reading": "よる", "en": "night"},
        {"jp": "刻む", "reading": "きざむ", "en": "to measure / mark time"},
        {"jp": "刻んでいた", "en": "measured", **_P},
        {"jp": "夜を刻んでいた", "en": "measured the night", **_P},
        {"jp": "職人の息だけが　夜を刻んでいた", "en": "…while only the craftsman's breath measured the night", **_P},
    ],
    "left": [
        {"jp": "細い", "reading": "ほそい", "en": "narrow"},
        {"jp": "路地", "reading": "ろじ", "en": "alley"},
        {"jp": "細い路地", "en": "the narrow alley", **_P},
        {"jp": "細い路地に", "en": "in the narrow alley", **_P},
        {"jp": "印", "reading": "しるし", "en": "sign / mark"},
        {"jp": "左へ", "reading": "ひだりへ", "en": "to the left"},
        {"jp": "左への印", "en": "a sign pointed left", **_P},
        {"jp": "細い路地に　左への印", "en": "In the narrow alley a sign pointed left", **_P},
        {"jp": "左", "reading": "ひだり", "en": "left"},
        {"jp": "知らない", "reading": "しらない", "en": "unfamiliar / unknown"},
        {"jp": "灯り", "reading": "あかり", "en": "lantern / lamplight"},
        {"jp": "知らない灯り", "en": "an unfamiliar lantern", **_P},
        {"jp": "知らない灯りが", "en": "an unfamiliar lantern", **_P},
        {"jp": "奥", "reading": "おく", "en": "deeper within"},
        {"jp": "揺れる", "reading": "ゆれる", "en": "to flicker / sway"},
        {"jp": "揺れていた", "en": "flickered", **_P},
        {"jp": "奥で揺れていた", "en": "flickered deeper within", **_P},
        {"jp": "知らない灯りが　奥で揺れていた", "en": "…and an unfamiliar lantern flickered deeper within", **_P},
    ],
    "right": [
        {"jp": "曲がる", "reading": "まがる", "en": "to turn / bend"},
        {"jp": "道", "reading": "みち", "en": "road / path"},
        {"jp": "右へ", "reading": "みぎへ", "en": "to the right"},
        {"jp": "右へ曲がる", "en": "turning right", **_P},
        {"jp": "右へ曲がる道", "en": "the road turning right", **_P},
        {"jp": "右へ曲がる道に", "en": "along the road turning right", **_P},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "伸びる", "reading": "のびる", "en": "to stretch"},
        {"jp": "伸び", "en": "stretched", **_P},
        {"jp": "影が伸び", "en": "shadows stretched", **_P},
        {"jp": "右へ曲がる道に　影が伸び", "en": "Along the road turning right, shadows stretched", **_P},
        {"jp": "右", "reading": "みぎ", "en": "right"},
        {"jp": "古い", "reading": "ふるい", "en": "old"},
        {"jp": "街並み", "reading": "まちなみ", "en": "townscape / old town"},
        {"jp": "古い街並み", "en": "the old town", **_P},
        {"jp": "古い街並みが", "en": "the old town", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "続く", "reading": "つづく", "en": "to continue / carry on"},
        {"jp": "静かに続いていた", "en": "carried on in silence", **_P},
        {"jp": "古い街並みが　静かに続いていた", "en": "…and the old town carried on in silence", **_P},
    ],
    "possess": [
        {"jp": "古い", "reading": "ふるい", "en": "old"},
        {"jp": "宝", "reading": "たから", "en": "treasure"},
        {"jp": "古い宝", "en": "an old treasure", **_P},
        {"jp": "古い宝を", "en": "an old treasure", **_P},
        {"jp": "手", "reading": "て", "en": "hands"},
        {"jp": "中", "reading": "なか", "en": "within"},
        {"jp": "手の中", "en": "within her hands", **_P},
        {"jp": "包む", "reading": "つつむ", "en": "to wrap / enfold"},
        {"jp": "包み", "en": "rested within", **_P},
        {"jp": "手の中に包み", "en": "rested within her hands", **_P},
        {"jp": "有", "reading": "ゆう", "en": "to possess / have"},
        {"jp": "持つ", "reading": "もつ", "en": "to hold / possess"},
        {"jp": "という", "reading": "という", "en": "called / of"},
        {"jp": "幸せ", "reading": "しあわせ", "en": "happiness"},
        {"jp": "持つという幸せ", "en": "the happiness of possessing it", **_P},
        {"jp": "持つという幸せが", "en": "the happiness of possessing it", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "満ちる", "reading": "みちる", "en": "to fill"},
        {"jp": "満ちていた", "en": "filled", **_P},
        {"jp": "静かに満ちていた", "en": "quietly filled", **_P},
        {"jp": "持つという幸せが　静かに満ちていた", "en": "…the happiness of possessing it quietly filled her heart", **_P},
    ],
    "bribe": [
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "静かな部屋", "en": "a quiet room", **_P},
        {"jp": "静かな部屋で", "en": "in a quiet room", **_P},
        {"jp": "包み", "reading": "つつみ", "en": "wrapped package"},
        {"jp": "置く", "reading": "おく", "en": "to set down"},
        {"jp": "置かれ", "en": "was set down", **_P},
        {"jp": "包みが置かれ", "en": "a wrapped package was set down", **_P},
        {"jp": "静かな部屋で　包みが置かれ", "en": "In a quiet room a wrapped package was set down", **_P},
        {"jp": "賄", "reading": "わい", "en": "bribe"},
        {"jp": "誰も", "reading": "だれも", "en": "no one / nobody"},
        {"jp": "語る", "reading": "かたる", "en": "to speak"},
        {"jp": "語らぬ", "en": "without a word being spoken", **_P},
        {"jp": "誰も語らぬまま", "en": "without a word being spoken", **_P},
        {"jp": "話", "reading": "はなし", "en": "discussion"},
        {"jp": "進む", "reading": "すすむ", "en": "to proceed / move forward"},
        {"jp": "進んでいった", "en": "moved forward", **_P},
        {"jp": "話は進んでいった", "en": "the discussion moved forward", **_P},
        {"jp": "誰も語らぬまま　話は進んでいった", "en": "…without a word being spoken, the discussion moved forward", **_P},
    ],
    "tribute": [
        {"jp": "捧げる", "reading": "ささげる", "en": "to offer / dedicate"},
        {"jp": "捧げられた", "en": "offered", **_P},
        {"jp": "箱", "reading": "はこ", "en": "chest / box"},
        {"jp": "捧げられた箱", "en": "the offered chest", **_P},
        {"jp": "捧げられた箱に", "en": "within the offered chest", **_P},
        {"jp": "金貨", "reading": "きんか", "en": "coins"},
        {"jp": "重なる", "reading": "かさなる", "en": "to pile up / gather"},
        {"jp": "重なり", "en": "gathered", **_P},
        {"jp": "金貨が重なり", "en": "coins gathered", **_P},
        {"jp": "捧げられた箱に　金貨が重なり", "en": "Coins gathered within the offered chest", **_P},
        {"jp": "貢", "reading": "こう", "en": "tribute"},
        {"jp": "人々", "reading": "ひとびと", "en": "people"},
        {"jp": "敬意", "reading": "けいい", "en": "respect"},
        {"jp": "人々の敬意", "en": "the people's respect", **_P},
        {"jp": "人々の敬意が", "en": "the people's respect", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "形", "reading": "かたち", "en": "form"},
        {"jp": "形となった", "en": "took form", **_P},
        {"jp": "静かに形となった", "en": "quietly took form", **_P},
        {"jp": "人々の敬意が　静かに形となった", "en": "…and the people's respect quietly took form", **_P},
    ],
    "paragraph": [
        {"jp": "古い", "reading": "ふるい", "en": "ancient / old"},
        {"jp": "書物", "reading": "しょもつ", "en": "book / writings"},
        {"jp": "古い書物", "en": "the ancient pages", **_P},
        {"jp": "古い書物を", "en": "the ancient pages", **_P},
        {"jp": "指", "reading": "ゆび", "en": "finger"},
        {"jp": "なぞる", "reading": "なぞる", "en": "to trace"},
        {"jp": "指でなぞりながら", "en": "tracing with a finger", **_P},
        {"jp": "古い書物を　指でなぞりながら", "en": "Tracing the ancient pages with a finger", **_P},
        {"jp": "項", "reading": "こう", "en": "paragraph / item"},
        {"jp": "一つ", "reading": "ひとつ", "en": "a single"},
        {"jp": "段落", "reading": "だんらく", "en": "paragraph"},
        {"jp": "一つの段落", "en": "a single paragraph", **_P},
        {"jp": "一つの段落が", "en": "a single paragraph", **_P},
        {"jp": "時", "reading": "とき", "en": "time / years"},
        {"jp": "越える", "reading": "こえる", "en": "to cross / span"},
        {"jp": "語りかける", "reading": "かたりかける", "en": "to speak across"},
        {"jp": "時を越えて語りかける", "en": "spoke across the years", **_P},
        {"jp": "一つの段落が　時を越えて語りかける", "en": "…a single paragraph spoke across the years", **_P},
    ],
    "sword": [
        {"jp": "朝日", "reading": "あさひ", "en": "morning light"},
        {"jp": "中", "reading": "なか", "en": "within"},
        {"jp": "朝日の中", "en": "the morning light", **_P},
        {"jp": "朝日の中で", "en": "within the morning light", **_P},
        {"jp": "刀", "reading": "とう", "en": "sword"},
        {"jp": "眠る", "reading": "ねむる", "en": "to rest / lie sleeping"},
        {"jp": "刀は眠り", "en": "the sword lay resting", **_P},
        {"jp": "朝日の中で　刀は眠り", "en": "Within the morning light the sword lay resting", **_P},
        {"jp": "触れる", "reading": "ふれる", "en": "to touch"},
        {"jp": "触れぬ", "en": "untouchable", **_P},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "触れぬ静けさ", "en": "an untouchable stillness", **_P},
        {"jp": "触れぬ静けさが", "en": "an untouchable stillness", **_P},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "満たす", "reading": "みたす", "en": "to fill"},
        {"jp": "満たしていた", "en": "filled", **_P},
        {"jp": "部屋を満たしていた", "en": "filled the room", **_P},
        {"jp": "触れぬ静けさが　部屋を満たしていた", "en": "…an untouchable stillness filled the room", **_P},
    ],
    "blade": [
        {"jp": "細い", "reading": "ほそい", "en": "fine / slender"},
        {"jp": "刃", "reading": "は", "en": "blade / edge"},
        {"jp": "先", "reading": "さき", "en": "tip / point"},
        {"jp": "刃先", "reading": "はさき", "en": "blade tip", **_P},
        {"jp": "細い刃先", "en": "the blade", **_P},
        {"jp": "細い刃先に", "en": "upon the blade", **_P},
        {"jp": "冷たい", "reading": "つめたい", "en": "cold"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "冷たい光", "en": "cold light", **_P},
        {"jp": "細い刃先に　冷たい光", "en": "Cold light rested upon the blade", **_P},
        {"jp": "わずか", "reading": "わずか", "en": "slight / slightest"},
        {"jp": "動き", "reading": "うごき", "en": "movement"},
        {"jp": "わずかな動き", "en": "the slightest movement", **_P},
        {"jp": "わずかな動きが", "en": "the slightest movement", **_P},
        {"jp": "運命", "reading": "うんめい", "en": "fate"},
        {"jp": "分ける", "reading": "わける", "en": "to divide"},
        {"jp": "分けてゆく", "en": "divided fate", **_P},
        {"jp": "運命を分けてゆく", "en": "divided fate", **_P},
        {"jp": "わずかな動きが　運命を分けてゆく", "en": "…where the slightest movement divided fate", **_P},
    ],
    "cut": [
        {"jp": "黒い", "reading": "くろい", "en": "dark / black"},
        {"jp": "裂け目", "reading": "さけめ", "en": "incision / fissure"},
        {"jp": "黒い裂け目", "en": "a dark incision", **_P},
        {"jp": "黒い裂け目が", "en": "a dark incision", **_P},
        {"jp": "夜", "reading": "よる", "en": "night"},
        {"jp": "断ち切る", "reading": "たちきる", "en": "to split apart"},
        {"jp": "断ち切り", "en": "split apart", **_P},
        {"jp": "夜を断ち切り", "en": "split the night apart", **_P},
        {"jp": "黒い裂け目が　夜を断ち切り", "en": "A dark incision split the night apart", **_P},
        {"jp": "切", "reading": "きる", "en": "to cut"},
        {"jp": "一瞬", "reading": "いっしゅん", "en": "a single flash / instant"},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "一瞬の光", "en": "a single flash", **_P},
        {"jp": "一瞬の光が", "en": "a single flash", **_P},
        {"jp": "静寂", "reading": "せいじゃく", "en": "silence"},
        {"jp": "貫く", "reading": "つらぬく", "en": "to pierce"},
        {"jp": "貫いていた", "en": "pierced", **_P},
        {"jp": "静寂を貫いていた", "en": "pierced the silence", **_P},
        {"jp": "一瞬の光が　静寂を貫いていた", "en": "…and a single flash pierced the silence", **_P},
    ],
    "seduce": [
        {"jp": "差し出す", "reading": "さしだす", "en": "to offer / hold out"},
        {"jp": "差し出された", "en": "offered", **_P},
        {"jp": "餌", "reading": "えさ", "en": "food / bait"},
        {"jp": "差し出された餌", "en": "the offered food", **_P},
        {"jp": "差し出された餌へ", "en": "toward the offered food", **_P},
        {"jp": "鯉", "reading": "こい", "en": "koi"},
        {"jp": "集まる", "reading": "あつまる", "en": "to gather"},
        {"jp": "鯉たちが集まり", "en": "the koi gathered", **_P},
        {"jp": "差し出された餌へ　鯉たちが集まり", "en": "Toward the offered food the koi gathered", **_P},
        {"jp": "召", "reading": "めす", "en": "to summon / seduce"},
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "水面", "reading": "すいめん", "en": "surface (of water)"},
        {"jp": "静かな水面", "en": "the quiet surface", **_P},
        {"jp": "静かな水面に", "en": "across the quiet surface", **_P},
        {"jp": "波", "reading": "なみ", "en": "ripples / waves"},
        {"jp": "広がる", "reading": "ひろがる", "en": "to spread outward"},
        {"jp": "広がった", "en": "spread outward", **_P},
        {"jp": "波が広がった", "en": "ripples spread outward", **_P},
        {"jp": "静かな水面に　波が広がった", "en": "…across the quiet surface ripples spread outward", **_P},
    ],
    "shining": [
        {"jp": "森", "reading": "もり", "en": "forest"},
        {"jp": "奥", "reading": "おく", "en": "depths / deep within"},
        {"jp": "森の奥", "en": "deep into the forest", **_P},
        {"jp": "森の奥へ", "en": "deep into the forest", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "差し込む", "reading": "さしこむ", "en": "to pour in / shine through"},
        {"jp": "光が差し込み", "en": "light poured", **_P},
        {"jp": "森の奥へ　光が差し込み", "en": "Light poured deep into the forest", **_P},
        {"jp": "昭", "reading": "しょう", "en": "shining / bright"},
        {"jp": "立つ", "reading": "たつ", "en": "to stand"},
        {"jp": "人", "reading": "ひと", "en": "person / figure"},
        {"jp": "立つ人", "en": "the standing figure", **_P},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "立つ人の影", "en": "the standing figure's shadow", **_P},
        {"jp": "立つ人の影が", "en": "the standing figure", **_P},
        {"jp": "金色", "reading": "きんいろ", "en": "gold"},
        {"jp": "包む", "reading": "つつむ", "en": "to wrap / enfold"},
        {"jp": "包まれていた", "en": "was wrapped", **_P},
        {"jp": "金色に包まれていた", "en": "was wrapped in gold", **_P},
        {"jp": "立つ人の影が　金色に包まれていた", "en": "…and the standing figure was wrapped in gold", **_P},
    ],
    "rule": [
        {"jp": "古い", "reading": "ふるい", "en": "ancient / old"},
        {"jp": "法", "reading": "ほう", "en": "law"},
        {"jp": "書", "reading": "しょ", "en": "book / writings"},
        {"jp": "古い法の書", "en": "the ancient law", **_P},
        {"jp": "古い法の書に", "en": "beside the ancient law", **_P},
        {"jp": "蝋燭", "reading": "ろうそく", "en": "candle"},
        {"jp": "揺れる", "reading": "ゆれる", "en": "to flicker"},
        {"jp": "蝋燭が揺れ", "en": "candles flickered", **_P},
        {"jp": "古い法の書に　蝋燭が揺れ", "en": "Candles flickered beside the ancient law", **_P},
        {"jp": "則", "reading": "そく", "en": "rule / law"},
        {"jp": "村人", "reading": "むらびと", "en": "villagers"},
        {"jp": "村人たち", "en": "the villagers", **_P},
        {"jp": "村人たちは", "en": "the villagers", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "耳", "reading": "みみ", "en": "ears"},
        {"jp": "傾ける", "reading": "かたむける", "en": "to incline / listen"},
        {"jp": "耳を傾けていた", "en": "sat quietly, listening", **_P},
        {"jp": "村人たちは静かに　耳を傾けていた", "en": "…and the villagers sat quietly, listening to its words", **_P},
    ],
    "vice": [
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to sit side by side"},
        {"jp": "並んで", "en": "seated side by side", **_P},
        {"jp": "座る", "reading": "すわる", "en": "to sit"},
        {"jp": "並んで座る", "en": "seated side by side", **_P},
        {"jp": "二人", "reading": "ふたり", "en": "two people"},
        {"jp": "並んで座る二人", "en": "the two seated figures", **_P},
        {"jp": "間", "reading": "あいだ", "en": "between"},
        {"jp": "並んで座る二人の間に", "en": "Between the two seated figures", **_P},
        {"jp": "副", "reading": "ふく", "en": "vice / secondary"},
        {"jp": "語る", "reading": "かたる", "en": "to speak"},
        {"jp": "語られぬ", "en": "unspoken", **_P},
        {"jp": "力", "reading": "ちから", "en": "power"},
        {"jp": "語られぬ力", "en": "unspoken power", **_P},
        {"jp": "語られぬ力が", "en": "unspoken power", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "流れる", "reading": "ながれる", "en": "to move / flow"},
        {"jp": "流れていた", "en": "moved", **_P},
        {"jp": "静かに流れていた", "en": "quietly moved", **_P},
        {"jp": "語られぬ力が　静かに流れていた", "en": "…unspoken power quietly moved", **_P},
    ],
    "separate": [
        {"jp": "壁", "reading": "かべ", "en": "wall"},
        {"jp": "背", "reading": "せ", "en": "back"},
        {"jp": "背にする", "reading": "せにする", "en": "to turn one's back to"},
        {"jp": "壁を背にして", "en": "Leaning against the wall", **_P},
        {"jp": "互い", "reading": "たがい", "en": "each other"},
        {"jp": "離れる", "reading": "はなれる", "en": "to turn apart / separate"},
        {"jp": "互いに離れ", "en": "they turned apart", **_P},
        {"jp": "壁を背にして　互いに離れ", "en": "Leaning against the wall, they turned apart", **_P},
        {"jp": "別", "reading": "べつ", "en": "separate / apart"},
        {"jp": "同じ", "reading": "おなじ", "en": "same"},
        {"jp": "空気", "reading": "くうき", "en": "air"},
        {"jp": "同じ空気", "en": "the same air", **_P},
        {"jp": "同じ空気だけ", "en": "only the same air", **_P},
        {"jp": "同じ空気だけが", "en": "only the same air", **_P},
        {"jp": "二人", "reading": "ふたり", "en": "the two of them"},
        {"jp": "結ぶ", "reading": "むすぶ", "en": "to connect / bind"},
        {"jp": "結んでいた", "en": "connected them", **_P},
        {"jp": "二人を結んでいた", "en": "connected them", **_P},
        {"jp": "同じ空気だけが　二人を結んでいた", "en": "…while only the same air connected them", **_P},
    ],
    "street": [
        {"jp": "朝霧", "reading": "あさぎり", "en": "morning mist"},
        {"jp": "街", "reading": "まち", "en": "city / town"},
        {"jp": "朝霧の街", "en": "the morning city", **_P},
        {"jp": "朝霧の街に", "en": "across the morning city", **_P},
        {"jp": "幾つ", "reading": "いくつ", "en": "many / several"},
        {"jp": "道", "reading": "みち", "en": "roads"},
        {"jp": "幾つもの道", "en": "many roads", **_P},
        {"jp": "伸び", "en": "stretched", **_P},
        {"jp": "幾つもの道が伸び", "en": "many roads stretched outward", **_P},
        {"jp": "朝霧の街に　幾つもの道が伸び", "en": "Across the morning city, many roads stretched outward", **_P},
        {"jp": "丁", "reading": "ちょう", "en": "street / city block"},
        {"jp": "遠い", "reading": "とおい", "en": "distant"},
        {"jp": "海", "reading": "うみ", "en": "sea"},
        {"jp": "遠い海", "en": "the distant sea", **_P},
        {"jp": "遠い海まで", "en": "all the way to the distant sea", **_P},
        {"jp": "人", "reading": "ひと", "en": "people"},
        {"jp": "流れ", "reading": "ながれ", "en": "flow"},
        {"jp": "人の流れ", "en": "the flow of people", **_P},
        {"jp": "人の流れが", "en": "the flow of people", **_P},
        {"jp": "続いていた", "en": "continued", **_P},
        {"jp": "人の流れが続いていた", "en": "the flow of people continued", **_P},
        {"jp": "遠い海まで　人の流れが続いていた", "en": "…and the flow of people continued all the way to the distant sea", **_P},
    ],
    "town": [
        {"jp": "夕暮れ", "reading": "ゆうぐれ", "en": "evening / dusk"},
        {"jp": "町", "reading": "まち", "en": "town"},
        {"jp": "夕暮れの町", "en": "the evening town", **_P},
        {"jp": "夕暮れの町に", "en": "throughout the evening town", **_P},
        {"jp": "灯り", "reading": "あかり", "en": "lights"},
        {"jp": "ともる", "reading": "ともる", "en": "to awaken / light up"},
        {"jp": "灯りがともり", "en": "lights awakened", **_P},
        {"jp": "夕暮れの町に　灯りがともり", "en": "Lights awakened throughout the evening town", **_P},
        {"jp": "人々", "reading": "ひとびと", "en": "human / people's"},
        {"jp": "声", "reading": "こえ", "en": "voices"},
        {"jp": "人々の声", "en": "human voices", **_P},
        {"jp": "人々の声が", "en": "human voices", **_P},
        {"jp": "窓辺", "reading": "まどべ", "en": "windows / window ledges"},
        {"jp": "溶ける", "reading": "とける", "en": "to melt / dissolve"},
        {"jp": "溶けてゆく", "en": "melted into", **_P},
        {"jp": "窓辺に溶けてゆく", "en": "melted into the windows", **_P},
        {"jp": "人々の声が　窓辺に溶けてゆく", "en": "…and human voices melted into the windows", **_P},
    ],
    "possible": [
        {"jp": "雲", "reading": "くも", "en": "clouds"},
        {"jp": "向こう", "reading": "むこう", "en": "beyond"},
        {"jp": "雲の向こう", "en": "beyond the clouds", **_P},
        {"jp": "雲の向こうに", "en": "beyond the clouds", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "差す", "reading": "さす", "en": "to appear / shine"},
        {"jp": "光が差し", "en": "a light appeared", **_P},
        {"jp": "雲の向こうに　光が差し", "en": "Beyond the clouds a light appeared", **_P},
        {"jp": "可", "reading": "か", "en": "possible / acceptable"},
        {"jp": "まだ", "reading": "まだ", "en": "still / yet"},
        {"jp": "名", "reading": "な", "en": "name"},
        {"jp": "未来", "reading": "みらい", "en": "future"},
        {"jp": "まだ名もない未来", "en": "an unnamed future", **_P},
        {"jp": "まだ名もない未来が", "en": "an unnamed future", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "待つ", "reading": "まつ", "en": "to wait"},
        {"jp": "待っていた", "en": "waited", **_P},
        {"jp": "静かに待っていた", "en": "waited quietly", **_P},
        {"jp": "まだ名もない未来が　静かに待っていた", "en": "…and an unnamed future waited quietly", **_P},
    ],
    "top": [
        {"jp": "山", "reading": "やま", "en": "mountain"},
        {"jp": "頂", "reading": "いただき", "en": "summit / peak"},
        {"jp": "山の頂", "en": "the mountain summit", **_P},
        {"jp": "山の頂から", "en": "from the mountain summit", **_P},
        {"jp": "朝霧", "reading": "あさぎり", "en": "morning mist"},
        {"jp": "越える", "reading": "こえる", "en": "to go beyond"},
        {"jp": "朝霧を越えて", "en": "beyond the morning mist", **_P},
        {"jp": "山の頂から　朝霧を越えて", "en": "From the mountain summit, beyond the morning mist", **_P},
        {"jp": "遠い", "reading": "とおい", "en": "distant"},
        {"jp": "景色", "reading": "けしき", "en": "landscape / view"},
        {"jp": "遠い景色", "en": "a distant landscape", **_P},
        {"jp": "遠い景色が", "en": "a distant landscape", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet / quietly"},
        {"jp": "開く", "reading": "ひらく", "en": "to open"},
        {"jp": "開いていた", "en": "opened", **_P},
        {"jp": "静かに開いていた", "en": "quietly opened", **_P},
        {"jp": "遠い景色が　静かに開いていた", "en": "…a distant landscape quietly opened before him", **_P},
    ],
    "child": [
        {"jp": "小さな", "reading": "ちいさな", "en": "tiny"},
        {"jp": "足", "reading": "あし", "en": "feet"},
        {"jp": "小さな足", "en": "tiny feet", **_P},
        {"jp": "小さな足で", "en": "with tiny feet", **_P},
        {"jp": "石畳", "reading": "いしだたみ", "en": "stone road / pavement"},
        {"jp": "歩く", "reading": "あるく", "en": "to walk"},
        {"jp": "歩き", "en": "walked", **_P},
        {"jp": "石畳を歩き", "en": "walked the stone road", **_P},
        {"jp": "小さな足で　石畳を歩き", "en": "With tiny feet she walked the stone road", **_P},
        {"jp": "子", "reading": "こ", "en": "child"},
        {"jp": "知らない", "reading": "しらない", "en": "unknown"},
        {"jp": "世界", "reading": "せかい", "en": "world"},
        {"jp": "知らない世界", "en": "the unknown world", **_P},
        {"jp": "知らない世界が", "en": "the unknown world", **_P},
        {"jp": "少しずつ", "reading": "すこしずつ", "en": "slowly / little by little"},
        {"jp": "広がる", "reading": "ひろがる", "en": "to grow wider"},
        {"jp": "広がった", "en": "grew wider", **_P},
        {"jp": "少しずつ広がった", "en": "slowly grew wider", **_P},
        {"jp": "知らない世界が　少しずつ広がった", "en": "…and the unknown world slowly grew wider", **_P},
    ],
}
