"""Hand-curated vocabulary → phrase sequences for Lesson 1 Vocabulary Exhibition.

Kanji and content words are introduced individually; grammar folds into phrases.
If a word was already taught in this sequence, it reappears only inside a larger phrase.
"""

from __future__ import annotations

_P = {"phrase": True}

VOCABULARY_BY_SLUG: dict[str, list[dict]] = {
    "one": [
        {"jp": "木", "reading": "き", "en": "wood"},
        {"jp": "床", "reading": "ゆか", "en": "floor"},
        {"jp": "木の床", "en": "the wooden floor", **_P},
        {"jp": "木の床に", "en": "upon the wooden floor", **_P},
        {"jp": "一", "reading": "ひと", "en": "one"},
        {"jp": "一つ", "en": "one / a single", **_P},
        {"jp": "柿", "reading": "かき", "en": "persimmon"},
        {"jp": "一つの柿", "en": "a single persimmon", **_P},
        {"jp": "光る", "reading": "ひかる", "en": "to glow"},
        {"jp": "光り", "reading": "ひかり", "en": "a glow", **_P},
        {"jp": "一つの柿が光り", "en": "a single persimmon glowed", **_P},
        {"jp": "木の床に　一つの柿が光り", "en": "A single persimmon glowed upon the wooden floor", **_P},
        {"jp": "障子", "reading": "しょうじ", "en": "shoji (paper screen door)"},
        {"jp": "午後", "reading": "ごご", "en": "afternoon"},
        {"jp": "障子の午後", "en": "afternoon through the shoji", **_P},
        {"jp": "静けさ", "reading": "しずけさ", "en": "stillness"},
        {"jp": "包む", "reading": "つつむ", "en": "to enfold / wrap"},
        {"jp": "静けさを包む", "en": "held the room in stillness", **_P},
        {"jp": "障子の午後が　静けさを包む", "en": "…while afternoon light through the shoji held the room in stillness", **_P},
    ],
    "two": [
        {"jp": "夜", "reading": "よる", "en": "night"},
        {"jp": "寺", "reading": "てら", "en": "temple"},
        {"jp": "夜の寺", "en": "the temple at night", **_P},
        {"jp": "夜の寺に", "en": "at the temple at night", **_P},
        {"jp": "二", "reading": "ふた", "en": "two"},
        {"jp": "二つ", "en": "two", **_P},
        {"jp": "灯", "reading": "あかり", "en": "lantern light"},
        {"jp": "二つの灯", "en": "two lanterns", **_P},
        {"jp": "浮かぶ", "reading": "うかぶ", "en": "to drift / float"},
        {"jp": "浮かび", "reading": "うかび", "en": "drifting", **_P},
        {"jp": "二つの灯が浮かび", "en": "two lanterns drifted", **_P},
        {"jp": "夜の寺に　二つの灯が浮かび", "en": "Two lanterns drifted above the temple at night", **_P},
        {"jp": "やわらか", "reading": "やわらか", "en": "gentle / soft"},
        {"jp": "闇", "reading": "やみ", "en": "darkness"},
        {"jp": "やわらかな闇", "en": "gentle darkness", **_P},
        {"jp": "やわらかな闇だけ", "en": "only the gentle darkness", **_P},
        {"jp": "揺れる", "reading": "ゆれる", "en": "to sway"},
        {"jp": "揺れていた", "en": "was swaying", **_P},
        {"jp": "やわらかな闇だけが　揺れていた", "en": "while only the gentle darkness swayed", **_P},
    ],
    "three": [
        {"jp": "黒い", "reading": "くろい", "en": "black"},
        {"jp": "台", "reading": "だい", "en": "stand / tray"},
        {"jp": "黒い台", "en": "the dark stand", **_P},
        {"jp": "黒い台に", "en": "upon the dark stand", **_P},
        {"jp": "三", "reading": "みっ", "en": "three"},
        {"jp": "三つ", "en": "three", **_P},
        {"jp": "三つの柿", "en": "three persimmons", **_P},
        {"jp": "並ぶ", "reading": "ならぶ", "en": "to line up"},
        {"jp": "並び", "reading": "ならび", "en": "lined up", **_P},
        {"jp": "三つの柿が並び", "en": "three persimmons lined up", **_P},
        {"jp": "黒い台に　三つの柿が並び", "en": "Three persimmons rested upon the dark tray", **_P},
        {"jp": "扇", "reading": "おうぎ", "en": "folding fan"},
        {"jp": "そば", "reading": "そば", "en": "beside"},
        {"jp": "扇のそば", "en": "beside the fan", **_P},
        {"jp": "扇のそばで", "en": "beside the folded fan", **_P},
        {"jp": "秋", "reading": "あき", "en": "autumn"},
        {"jp": "息づく", "reading": "いきづく", "en": "to stir to life / breathe"},
        {"jp": "秋が息づいていた", "en": "autumn quietly breathed", **_P},
        {"jp": "扇のそばで　秋が息づいていた", "en": "…and beside the folded fan, autumn quietly breathed", **_P},
    ],
    "four": [
        {"jp": "四", "reading": "よ", "en": "four"},
        {"jp": "四つ", "en": "four", **_P},
        {"jp": "四つの柿", "en": "four persimmons", **_P},
        {"jp": "盆", "reading": "ぼん", "en": "tray"},
        {"jp": "上", "reading": "うえ", "en": "top / upon"},
        {"jp": "盆の上", "en": "upon the tray", **_P},
        {"jp": "盆の上に", "en": "upon the tray", **_P},
        {"jp": "四つの柿が　盆の上に並び", "en": "Four persimmons lined up upon the tray", **_P},
        {"jp": "影", "reading": "かげ", "en": "shadow"},
        {"jp": "障子の影", "en": "shadows on the shoji", **_P},
        {"jp": "部屋", "reading": "へや", "en": "room"},
        {"jp": "秋の部屋", "en": "the autumn room", **_P},
        {"jp": "秋の部屋を包む", "en": "wrapped the autumn room", **_P},
        {"jp": "障子の影が　秋の部屋を包む", "en": "…while maple shadows on the shoji wrapped the autumn room", **_P},
    ],
    "five": [
        {"jp": "五", "reading": "いつ", "en": "five"},
        {"jp": "五つ", "en": "five", **_P},
        {"jp": "鯉", "reading": "こい", "en": "carp"},
        {"jp": "のぼり", "reading": "のぼり", "en": "streamer"},
        {"jp": "鯉のぼり", "en": "carp streamer", **_P},
        {"jp": "五つの鯉のぼり", "en": "five carp streamers", **_P},
        {"jp": "風", "reading": "かぜ", "en": "wind"},
        {"jp": "泳ぐ", "reading": "およぐ", "en": "to swim"},
        {"jp": "泳ぎ", "reading": "およぎ", "en": "swimming", **_P},
        {"jp": "風に泳ぎ", "en": "swimming in the wind", **_P},
        {"jp": "五つの鯉のぼりが　風に泳ぎ", "en": "Five carp streamed in the wind above the river", **_P},
        {"jp": "川", "reading": "かわ", "en": "river"},
        {"jp": "川の上", "en": "above the river", **_P},
        {"jp": "川の上だけ", "en": "only above the river", **_P},
        {"jp": "春", "reading": "はる", "en": "spring"},
        {"jp": "映す", "reading": "うつす", "en": "to reflect / mirror"},
        {"jp": "春を映していた", "en": "mirrored the spring", **_P},
        {"jp": "川の上だけが　春を映していた", "en": "…while only the water mirrored the spring", **_P},
    ],
    "six": [
        {"jp": "六", "reading": "むっ", "en": "six"},
        {"jp": "六つ", "en": "six", **_P},
        {"jp": "茶碗", "reading": "ちゃわん", "en": "tea bowl"},
        {"jp": "六つの茶碗", "en": "six tea bowls", **_P},
        {"jp": "六つの茶碗に", "en": "in six tea bowls", **_P},
        {"jp": "湯気", "reading": "ゆげ", "en": "rising steam"},
        {"jp": "立つ", "reading": "たつ", "en": "to rise"},
        {"jp": "湯気が立ち", "en": "steam rose", **_P},
        {"jp": "六つの茶碗に　湯気が立ち", "en": "Steam rose from six tea bowls in a row", **_P},
        {"jp": "静か", "reading": "しずか", "en": "quiet"},
        {"jp": "席", "reading": "せき", "en": "seat"},
        {"jp": "静かな席", "en": "the quiet seats", **_P},
        {"jp": "人", "reading": "ひと", "en": "person"},
        {"jp": "待つ", "reading": "まつ", "en": "to wait"},
        {"jp": "人を待っていた", "en": "waited for their guests", **_P},
        {"jp": "静かな席が　人を待っていた", "en": "…while the quiet seats waited for their guests", **_P},
    ],
    "seven": [
        {"jp": "七", "reading": "なな", "en": "seven"},
        {"jp": "匹", "reading": "ひき", "en": "counter (small animals)"},
        {"jp": "七匹", "reading": "ななひき", "en": "seven (animals)", **_P},
        {"jp": "七匹の鯉", "en": "seven koi", **_P},
        {"jp": "池", "reading": "いけ", "en": "pond"},
        {"jp": "池を泳ぎ", "en": "glided through the pond", **_P},
        {"jp": "七匹の鯉が　池を泳ぎ", "en": "Seven koi glided through the moonlit pond", **_P},
        {"jp": "一匹", "reading": "いっぴき", "en": "one (animal)", **_P},
        {"jp": "一匹だけ", "en": "one alone", **_P},
        {"jp": "月", "reading": "つき", "en": "moon"},
        {"jp": "向かう", "reading": "むかう", "en": "to head toward"},
        {"jp": "月へ向かっていた", "en": "turned toward the moon", **_P},
        {"jp": "一匹だけが　月へ向かっていた", "en": "…while one alone turned toward the moon", **_P},
    ],
    "eight": [
        {"jp": "巨木", "reading": "きょぼく", "en": "great tree"},
        {"jp": "根", "reading": "ね", "en": "roots"},
        {"jp": "巨木の根", "en": "the roots of the great tree", **_P},
        {"jp": "巨木の根で", "en": "at the roots of the great tree", **_P},
        {"jp": "道", "reading": "みち", "en": "path"},
        {"jp": "二つ", "en": "two", **_P},
        {"jp": "裂ける", "reading": "さける", "en": "to split"},
        {"jp": "二つに裂け", "en": "split in two", **_P},
        {"jp": "道が二つに裂け", "en": "the path split in two", **_P},
        {"jp": "巨木の根で　道が二つに裂け", "en": "At the roots of the great tree the path split in two", **_P},
        {"jp": "旅", "reading": "たび", "en": "journey / travel"},
        {"jp": "旅人", "reading": "たびびと", "en": "traveler"},
        {"jp": "旅人だけ", "en": "the traveler alone", **_P},
        {"jp": "選択", "reading": "せんたく", "en": "choice"},
        {"jp": "止める", "reading": "とめる", "en": "to stop / pause"},
        {"jp": "選択を止めていた", "en": "paused before the choice", **_P},
        {"jp": "旅人だけが　選択を止めていた", "en": "…and the traveler alone paused before the choice", **_P},
    ],
    "nine": [
        {"jp": "濡れる", "reading": "ぬれる", "en": "to become wet"},
        {"jp": "濡れた", "en": "wet", **_P},
        {"jp": "橋", "reading": "はし", "en": "bridge"},
        {"jp": "濡れた橋", "en": "the wet bridge", **_P},
        {"jp": "濡れた橋に", "en": "across the wet bridge", **_P},
        {"jp": "灯り", "reading": "あかり", "en": "lamplight"},
        {"jp": "続く", "reading": "つづく", "en": "to continue"},
        {"jp": "灯りが続く", "en": "the lights continue", **_P},
        {"jp": "濡れた橋に　灯りが続く", "en": "Lights continuing across the wet bridge", **_P},
    ],
    "ten": [
        {"jp": "朝", "reading": "あさ", "en": "morning"},
        {"jp": "市", "reading": "いち", "en": "market"},
        {"jp": "朝の市", "en": "the morning market", **_P},
        {"jp": "朝の市で", "en": "at the morning market", **_P},
        {"jp": "藍", "reading": "あい", "en": "indigo"},
        {"jp": "布", "reading": "ぬの", "en": "cloth"},
        {"jp": "藍の布", "en": "indigo cloth", **_P},
        {"jp": "畳む", "reading": "たたむ", "en": "to fold"},
        {"jp": "藍の布を畳み", "en": "folded indigo cloth", **_P},
        {"jp": "朝の市で　藍の布を畳み", "en": "At the morning market he folded indigo cloth", **_P},
        {"jp": "十", "reading": "じゅう", "en": "ten"},
        {"jp": "交わり", "reading": "まじわり", "en": "crossing / intersection"},
        {"jp": "十の交わり", "en": "the crossing of ten", **_P},
        {"jp": "刻む", "reading": "きざむ", "en": "to carve / weave in"},
        {"jp": "布に静かに刻まれた", "en": "lay quietly woven in the fabric", **_P},
        {"jp": "十の交わりが　布に静かに刻まれた", "en": "…and the crossing of ten lay quietly woven in the fabric", **_P},
    ],
    "mouth": [
        {"jp": "湯気の立つ", "en": "the steaming …", **_P},
        {"jp": "碗", "reading": "わん", "en": "bowl"},
        {"jp": "湯気の立つ碗", "en": "the steaming bowl", **_P},
        {"jp": "両手", "reading": "りょうて", "en": "both hands"},
        {"jp": "両手で包み", "en": "holding in both hands", **_P},
        {"jp": "湯気の立つ碗を　両手で包み", "en": "Holding the steaming bowl in both hands", **_P},
        {"jp": "口", "reading": "くち", "en": "mouth"},
        {"jp": "開ける", "reading": "あける", "en": "to open"},
        {"jp": "口を開けて", "en": "she opened her mouth", **_P},
        {"jp": "笑い", "reading": "わらい", "en": "laughter"},
        {"jp": "溢れる", "reading": "あふれる", "en": "to overflow / fill"},
        {"jp": "笑いが部屋に溢れた", "en": "laughter filled the room", **_P},
        {"jp": "口を開けて　笑いが部屋に溢れた", "en": "…she opened her mouth and laughter filled the room", **_P},
    ],
    "sun": [
        {"jp": "棚田", "reading": "たなだ", "en": "terraced rice fields"},
        {"jp": "棚田に", "en": "across the terraced fields", **_P},
        {"jp": "日", "reading": "ひ", "en": "sun"},
        {"jp": "朝日", "reading": "あさひ", "en": "morning sun"},
        {"jp": "降り注ぐ", "reading": "ふりそそぐ", "en": "to pour down"},
        {"jp": "棚田に　朝日が降り注ぐ", "en": "Morning sun poured across the terraced fields", **_P},
        {"jp": "水面", "reading": "みなも", "en": "water's surface"},
        {"jp": "水面だけ", "en": "only the water's surface", **_P},
        {"jp": "黄金", "reading": "こがね", "en": "gold"},
        {"jp": "燃える", "reading": "もえる", "en": "to burn / glow"},
        {"jp": "黄金に燃えていた", "en": "burned with gold", **_P},
        {"jp": "水面だけが　黄金に燃えていた", "en": "…while only the water burned with gold", **_P},
    ],
    "moon": [
        {"jp": "船上", "reading": "せんじょう", "en": "onboard a boat"},
        {"jp": "船上で", "en": "upon the boat", **_P},
        {"jp": "網", "reading": "あみ", "en": "net"},
        {"jp": "直す", "reading": "なおす", "en": "to mend / repair"},
        {"jp": "網を直す", "en": "mending his net", **_P},
        {"jp": "漁師", "reading": "りょうし", "en": "fisherman"},
        {"jp": "網を直す漁師", "en": "a fisherman mending his net", **_P},
        {"jp": "船上で網を直す漁師に", "en": "to a fisherman mending his net upon the boat", **_P},
        {"jp": "あかり", "reading": "あかり", "en": "light"},
        {"jp": "月あかり", "reading": "つきあかり", "en": "moonlight"},
        {"jp": "月あかりだけ", "en": "only moonlight", **_P},
        {"jp": "寄り添う", "reading": "よりそう", "en": "to draw near / keep company"},
        {"jp": "静かに寄り添った", "en": "quietly kept him company", **_P},
        {"jp": "月あかりだけが　静かに寄り添った", "en": "…while moonlight alone quietly kept him company", **_P},
    ],
    "field": [
        {"jp": "方眼", "reading": "ほうがん", "en": "grid pattern"},
        {"jp": "田", "reading": "た", "en": "rice field"},
        {"jp": "方眼の田", "en": "the grid of paddies", **_P},
        {"jp": "映し", "reading": "うつし", "en": "mirrored", **_P},
        {"jp": "方眼の田が　朝日を映し", "en": "The grid of paddies mirrored the morning sun", **_P},
        {"jp": "霧", "reading": "きり", "en": "mist"},
        {"jp": "谷", "reading": "たに", "en": "valley"},
        {"jp": "霧の谷", "en": "the misty valley", **_P},
        {"jp": "霧の谷だけ", "en": "only the misty valley", **_P},
        {"jp": "静かに包んでいた", "en": "quietly held them", **_P},
        {"jp": "霧の谷だけが　静かに包んでいた", "en": "…while only the misty valley quietly held them", **_P},
    ],
    "eye": [
        {"jp": "橋の上", "en": "upon the bridge", **_P},
        {"jp": "橋の上で", "en": "upon the bridge", **_P},
        {"jp": "流れ", "reading": "ながれ", "en": "flow / drift"},
        {"jp": "灯りの流れ", "en": "the flow of lanterns", **_P},
        {"jp": "見つめる", "reading": "みつめる", "en": "to gaze at / watch"},
        {"jp": "灯りの流れを見つめ", "en": "watching the lanterns drift", **_P},
        {"jp": "橋の上で　灯りの流れを見つめ", "en": "Upon the bridge he watched the lanterns drift", **_P},
        {"jp": "少", "reading": "しょう", "en": "young"},
        {"jp": "年", "reading": "ねん", "en": "year"},
        {"jp": "少年", "reading": "しょうねん", "en": "boy"},
        {"jp": "目", "reading": "め", "en": "eye"},
        {"jp": "少年の目", "en": "the boy's eyes", **_P},
        {"jp": "少年の目だけ", "en": "only the boy's eyes", **_P},
        {"jp": "覚える", "reading": "おぼえる", "en": "to remember"},
        {"jp": "夜を覚えていた", "en": "remembered the night", **_P},
        {"jp": "少年の目だけが　夜を覚えていた", "en": "…while only the boy's eyes remembered the night", **_P},
    ],
    "old": [
        {"jp": "古い", "reading": "ふるい", "en": "old / ancient"},
        {"jp": "杉", "reading": "すぎ", "en": "cedar"},
        {"jp": "古い杉", "en": "an ancient cedar", **_P},
        {"jp": "幹", "reading": "みき", "en": "trunk"},
        {"jp": "古い杉の幹", "en": "the trunk of the ancient cedar", **_P},
        {"jp": "古い杉の幹に", "en": "upon the trunk of the ancient cedar", **_P},
        {"jp": "光", "reading": "ひかり", "en": "light"},
        {"jp": "朝の光", "en": "morning light", **_P},
        {"jp": "差す", "reading": "さす", "en": "to shine upon"},
        {"jp": "朝の光が差し", "en": "morning light touched", **_P},
        {"jp": "古い杉の幹に　朝の光が差し", "en": "Morning light touched the trunk of the ancient cedar", **_P},
        {"jp": "幾", "reading": "いく", "en": "several"},
        {"jp": "世代", "reading": "せだい", "en": "generations"},
        {"jp": "幾世代", "reading": "いくせだい", "en": "generations"},
        {"jp": "祈り", "reading": "いのり", "en": "prayer"},
        {"jp": "幾世代もの祈り", "en": "the prayers of generations", **_P},
        {"jp": "宿す", "reading": "やどす", "en": "to carry / dwell within"},
        {"jp": "幾世代もの祈りを　静かに宿していた", "en": "…which quietly carried the prayers of generations", **_P},
    ],
    "I": [
        {"jp": "鏡", "reading": "かがみ", "en": "mirror"},
        {"jp": "前", "reading": "まえ", "en": "before / in front"},
        {"jp": "鏡の前", "en": "before the mirror", **_P},
        {"jp": "鏡の前に", "en": "before the mirror", **_P},
        {"jp": "立つ", "reading": "たつ", "en": "to stand"},
        {"jp": "静かに立ち", "en": "stood quietly", **_P},
        {"jp": "鏡の前に　静かに立ち", "en": "He stood quietly before the mirror", **_P},
        {"jp": "言葉", "reading": "ことば", "en": "words"},
        {"jp": "言葉なくして", "en": "without words", **_P},
        {"jp": "我", "reading": "われ", "en": "I / oneself"},
        {"jp": "我だけ", "en": "only himself", **_P},
        {"jp": "在る", "reading": "ある", "en": "to be / exist"},
        {"jp": "我だけが在った", "en": "only himself remained", **_P},
        {"jp": "言葉なくして　我だけが在った", "en": "…and without words, only himself remained", **_P},
    ],
    "risk": [
        {"jp": "嶺", "reading": "みね", "en": "ridge / peak"},
        {"jp": "雪の嶺", "en": "the snowy ridge", **_P},
        {"jp": "雪の嶺で", "en": "upon the snowy ridge", **_P},
        {"jp": "伸ばす", "reading": "のばす", "en": "to extend / reach out"},
        {"jp": "伸ばした手", "en": "reaching hands", **_P},
        {"jp": "握る", "reading": "にぎる", "en": "to clasp / grasp"},
        {"jp": "伸ばした手を握り", "en": "they clasped reaching hands", **_P},
        {"jp": "雪の嶺で　伸ばした手を握り", "en": "Upon the snowy ridge they clasped reaching hands", **_P},
        {"jp": "見えぬ", "reading": "みえぬ", "en": "unseen"},
        {"jp": "歩", "reading": "ぽ", "en": "step"},
        {"jp": "一歩", "reading": "いっぽ", "en": "one step"},
        {"jp": "見えぬ一歩が", "en": "one unseen step …", **_P},
        {"jp": "二人", "reading": "ふたり", "en": "two people"},
        {"jp": "結ぶ", "reading": "むすぶ", "en": "to bind / join"},
        {"jp": "二人を結んでいた", "en": "bound them together", **_P},
        {"jp": "見えぬ一歩が　二人を結んでいた", "en": "…and one unseen step bound them together", **_P},
    ],
    "companion": [
        {"jp": "庭", "reading": "にわ", "en": "garden"},
        {"jp": "雪の庭", "en": "the snow-covered garden", **_P},
        {"jp": "向かい合う", "reading": "むかいあう", "en": "to face one another"},
        {"jp": "向かい合いながら", "en": "facing each other", **_P},
        {"jp": "雪の庭を　向かい合いながら", "en": "Facing each other across the snowy garden", **_P},
        {"jp": "火", "reading": "ひ", "en": "fire"},
        {"jp": "鉢", "reading": "ばち", "en": "brazier"},
        {"jp": "火鉢", "reading": "ひばち", "en": "brazier"},
        {"jp": "ぬくもり", "reading": "ぬくもり", "en": "warmth"},
        {"jp": "火鉢のぬくもり", "en": "the warmth of the brazier", **_P},
        {"jp": "火鉢のぬくもりだけ", "en": "only the warmth of the brazier", **_P},
        {"jp": "つなぐ", "reading": "つなぐ", "en": "to join / connect"},
        {"jp": "二人をつないでいた", "en": "joined them together", **_P},
        {"jp": "火鉢のぬくもりだけが　二人をつないでいた", "en": "…only the warmth of the brazier joined them together", **_P},
    ],
    "bright": [
        {"jp": "炉", "reading": "ろ", "en": "hearth"},
        {"jp": "炉の火", "en": "the hearth fire", **_P},
        {"jp": "顔", "reading": "かお", "en": "faces"},
        {"jp": "二人の顔", "en": "their faces", **_P},
        {"jp": "照らす", "reading": "てらす", "en": "to illuminate"},
        {"jp": "炉の火が　二人の顔を照らし", "en": "The hearth fire lit their faces with warmth", **_P},
        {"jp": "明るい", "reading": "あかるい", "en": "bright"},
        {"jp": "明るい笑い", "en": "their bright laughter", **_P},
        {"jp": "明るい笑いだけ", "en": "only their bright laughter", **_P},
        {"jp": "残る", "reading": "のこる", "en": "to linger / remain"},
        {"jp": "部屋に残った", "en": "lingered in the room", **_P},
        {"jp": "明るい笑いだけが　部屋に残った", "en": "…and only their bright laughter lingered in the room", **_P},
    ],
}
