"""Per-verse curation for mixed reading stage (Lessons 1–5 Verses exhibition).

Each scene lists only compounds or iconic nouns to reveal — typically 1–3 per verse.
Grammar, verbs, and abstract vocabulary stay in hiragana.
When in doubt, fewer reveals.
"""

from __future__ import annotations

# scene_id → kanji compounds / iconic nouns to keep in mixed stage
MIXED_REVEAL: dict[str, list[str]] = {
    # ── Lesson 1 ──
    "L01_one": ["柿", "障子"],
    "L01_two": ["寺", "灯"],
    "L01_three": ["柿"],
    "L01_four": ["柿", "障子"],
    "L01_five": ["鯉", "川"],
    "L01_six": ["茶碗"],
    "L01_seven": ["鯉", "月"],
    "L01_eight": ["道"],
    "L01_nine": ["橋"],
    "L01_ten": ["朝"],
    "L01_mouth": ["笑"],
    "L01_sun": ["朝日", "水面"],
    "L01_moon": ["月"],
    "L01_field": ["朝日"],
    "L01_eye": ["橋"],
    "L01_old": ["杉", "光"],
    "L01_I": ["鏡"],
    "L01_risk": ["雪", "山"],
    "L01_companion": ["雪", "庭"],
    "L01_bright": ["火"],
    # ── Lesson 2 ──
    "L02_prosperous": ["湖", "光"],
    "L02_chant": ["鐘"],
    "L02_sparkle": ["水晶", "森"],
    "L02_goods": ["障子"],
    "L02_spine": [],
    "L02_early": ["朝"],
    "L02_rising_sun": ["朝日", "山"],
    "L02_generation": ["湖"],
    "L02_stomach": ["山"],
    "L02_dawn": ["朝日"],
    "L02_gallbladder": [],
    "L02_span": ["川", "山"],
    "L02_concave": ["月"],
    "L02_convex": ["舟"],
    "L02_olden_times": ["夕日"],
    "L02_oneself": [],
    "L02_white": ["花"],
    "L02_hundred": ["鶴"],
    "L02_middle": [],
    "L02_thousand": ["鶴"],
    # ── Lesson 3 ──
    "L03_tongue": ["犬"],
    "L03_measuring_box": ["米"],
    "L03_rise": ["灯籠", "町"],
    "L03_round": ["石畳", "障子"],
    "L03_measurement": ["匠"],
    "L03_elbow": ["灯籠"],
    "L03_specialty": ["工房"],
    "L03_knowledgeable": ["本"],
    "L03_signal": ["山"],
    "L03_fortune_telling": ["神社"],
    "L03_up": ["空"],
    "L03_below": ["猫", "朝日"],
    "L03_eminent": ["梅"],
    "L03_morning": ["朝日", "里"],
    "L03_derision": ["門"],
    "L03_only": [],
    "L03_shellfish": ["貝", "波"],
    "L03_pop_song": [],
    "L03_virtue": ["雪", "灯籠"],
    "L03_employee": [],
    # ── Lesson 4 ──
    "L04_post_a_bill": ["街"],
    "L04_see": ["目"],
    "L04_newborn": ["命"],
    "L04_beginning": ["富士", "水面"],
    "L04_page": ["本"],
    "L04_stubborn": [],
    "L04_mediocre": [],
    "L04_defeat": [],
    "L04_ten_thousand": [],
    "L04_phrase": [],
    "L04_texture": ["布"],
    "L04_ten_days": ["風"],
    "L04_ladle": ["湯気"],
    "L04_bulls_eye": ["的"],
    "L04_neck": [],
    "L04_hook": ["部屋"],
    "L04_riot": ["街", "夜"],
    "L04_straightaway": ["道"],
    "L04_tool": [],
    "L04_true": [],
    # ── Lesson 5 ──
    "L05_craft": ["工房"],
    "L05_left": ["灯"],
    "L05_right": ["道", "街"],
    "L05_possess": ["宝"],
    "L05_bribe": [],
    "L05_tribute": ["金"],
    "L05_paragraph": ["書物"],
    "L05_sword": ["刀", "朝日"],
    "L05_blade": ["刃"],
    "L05_cut": ["夜"],
    "L05_seduce": ["鯉", "水面"],
    "L05_shining": ["森", "光"],
    "L05_rule": ["村"],
    "L05_vice": [],
    "L05_separate": [],
    "L05_street": ["街", "海"],
    "L05_town": ["町"],
    "L05_possible": ["雲"],
    "L05_top": ["山"],
    "L05_child": ["石畳"],
}

# Back-compat aliases for imports
MIXED_KEEP = MIXED_REVEAL
MIXED_COMPOUNDS: frozenset[str] = frozenset()
MIXED_SCENE_COMPOUNDS: dict[str, list[str]] = {}
