#!/usr/bin/env bash
# Serve the ambient player from this directory.
# Requires ./assets -> ../../assets (symlink) so /assets/studies/*.png resolves.
set -euo pipefail
cd "$(dirname "$0")"
if [[ ! -e assets/studies ]]; then
  echo "Missing assets link. Run: ln -s ../../assets assets" >&2
  exit 1
fi
if [[ ! -e strokes/pages ]]; then
  echo "Missing strokes link. Run: ln -s ../strokes strokes" >&2
  exit 1
fi
if [[ ! -e bookends/lesson_32.png ]]; then
  echo "Missing bookend artwork. Run: ln -s ../../../assets/covers/lesson_32.png bookends/lesson_32.png" >&2
  exit 1
fi
PORT="${1:-8765}"
echo "── Lesson 1 (six stages) ──"
echo "1 Foundations: http://localhost:${PORT}/index.html?collection=lesson_1_foundations&typography=mobile-refine"
echo "2 Reading:     http://localhost:${PORT}/exhibition.html?collection=lesson_01_reading"
echo "3 Vocabulary:  http://localhost:${PORT}/exhibition.html?collection=lesson_01_vocabulary"
echo "4 Strokes:     http://localhost:${PORT}/exhibition.html?collection=lesson_01_strokes"
echo "5 Compounds:   http://localhost:${PORT}/exhibition.html?collection=lesson_01_compounds"
echo "6 Gallery:     http://localhost:${PORT}/exhibition.html?collection=lesson_01_gallery"
echo ""
echo "── Lesson 2 ──"
echo "Reading:       http://localhost:${PORT}/exhibition.html?collection=lesson_02_reading"
echo "Vocabulary:    http://localhost:${PORT}/exhibition.html?collection=lesson_02_vocabulary"
echo "Strokes:       http://localhost:${PORT}/exhibition.html?collection=lesson_02_strokes"
echo "Compounds:     http://localhost:${PORT}/exhibition.html?collection=lesson_02_compounds"
echo "Gallery:       http://localhost:${PORT}/exhibition.html?collection=lesson_02_gallery"
echo ""
echo "── Lesson 3 ──"
echo "Reading:       http://localhost:${PORT}/exhibition.html?collection=lesson_03_reading"
echo "Vocabulary:    http://localhost:${PORT}/exhibition.html?collection=lesson_03_vocabulary"
echo "Strokes:       http://localhost:${PORT}/exhibition.html?collection=lesson_03_strokes"
echo "Compounds:     http://localhost:${PORT}/exhibition.html?collection=lesson_03_compounds"
echo "Gallery:       http://localhost:${PORT}/exhibition.html?collection=lesson_03_gallery"
echo ""
echo "── Lesson 4 ──"
echo "Reading:       http://localhost:${PORT}/exhibition.html?collection=lesson_04_reading"
echo "Vocabulary:    http://localhost:${PORT}/exhibition.html?collection=lesson_04_vocabulary"
echo "Strokes:       http://localhost:${PORT}/exhibition.html?collection=lesson_04_strokes"
echo "Compounds:     http://localhost:${PORT}/exhibition.html?collection=lesson_04_compounds"
echo "Gallery:       http://localhost:${PORT}/exhibition.html?collection=lesson_04_gallery"
echo ""
echo "── Lesson 5 ──"
echo "Reading:       http://localhost:${PORT}/exhibition.html?collection=lesson_05_reading"
echo "Vocabulary:    http://localhost:${PORT}/exhibition.html?collection=lesson_05_vocabulary"
echo "Strokes:       http://localhost:${PORT}/exhibition.html?collection=lesson_05_strokes"
echo "Compounds:     http://localhost:${PORT}/exhibition.html?collection=lesson_05_compounds"
echo "Gallery:       http://localhost:${PORT}/exhibition.html?collection=lesson_05_gallery"
echo ""
for n in $(seq 1 10); do
  echo "Foundations L${n}: http://localhost:${PORT}/index.html?collection=lesson_${n}_foundations&typography=mobile-refine"
done
for n in $(seq -w 2 10); do
  echo "Reading L${n}:     http://localhost:${PORT}/exhibition.html?collection=lesson_${n}_reading"
done
echo "YouTube L36:  http://localhost:${PORT}/index.html?collection=lesson_36_foundations"
echo "YouTube L37:  http://localhost:${PORT}/index.html?collection=lesson_37_foundations"
echo "YouTube L38:  http://localhost:${PORT}/index.html?collection=lesson_38_foundations"
echo "YouTube L39:  http://localhost:${PORT}/index.html?collection=lesson_39_foundations"
echo "YouTube L40:  http://localhost:${PORT}/index.html?collection=lesson_40_foundations"
echo "Exhibit L36:  http://localhost:${PORT}/index.html?collection=lesson_36_foundations&capture=1"
echo "Exhibit L37:  http://localhost:${PORT}/index.html?collection=lesson_37_foundations&capture=1"
echo "Exhibit L38:  http://localhost:${PORT}/index.html?collection=lesson_38_foundations&capture=1"
echo "Exhibit L39:  http://localhost:${PORT}/index.html?collection=lesson_39_foundations&capture=1"
echo "Exhibit L40:  http://localhost:${PORT}/index.html?collection=lesson_40_foundations&capture=1"
echo "Exhibit L41:  http://localhost:${PORT}/index.html?collection=lesson_41_foundations&capture=1"
echo "Exhibit L42:  http://localhost:${PORT}/index.html?collection=lesson_42_foundations&capture=1"
echo "Record MP4s:  ./scripts/record_foundations_exhibition.sh   (lessons 40–42)"
echo "Foundations L41: http://localhost:${PORT}/index.html?collection=lesson_41_foundations"
echo "Heart Expo:   http://localhost:${PORT}/exhibition.html?collection=heart_v5"
echo "Heart QA:     http://localhost:${PORT}/exhibition.html?collection=heart_v5&skipBookends=1&exhibit=0&singleExhibit=1"
echo "Heart record: fullscreen browser + OBS (~96 min). Save → heart_exhibitions/heart_v5.mp4"
echo "              Mux audio: audio/exhibition_flute_intro.mp3 @ 2s, then ambient_kanji_exhibition.mp3 after flute ends + 6s exhale"
echo "Party Kanji:  http://localhost:${PORT}/exhibition.html?collection=party_kanji_v1&skipBookends=1&singleExhibit=1"
echo "Party QA:     add &timingScale=0.05"
echo "── Japanese Vocabulary (separate curriculum; not Junior High) ──"
echo "Vocabulary Lesson 1: http://localhost:${PORT}/exhibition.html?collection=vocabulary_01"
echo "Vocabulary Lesson 2: http://localhost:${PORT}/exhibition.html?collection=vocabulary_02"
echo "Vocabulary Lesson 3: http://localhost:${PORT}/exhibition.html?collection=vocabulary_03"
echo "Vocabulary Lesson 4: http://localhost:${PORT}/exhibition.html?collection=vocabulary_04"
echo "  QA:         add &timingScale=0.05   (or &skipBookends=1&timingScale=0.05)"
echo ""
echo "Jōyō Soundtrack part 1 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_01"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording.sh"
echo "Jōyō Soundtrack part 2 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_02"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part2.sh"
echo "Jōyō Soundtrack part 3 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_03"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part3.sh"
echo "Jōyō Soundtrack part 4 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_04"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part4.sh"
echo "Jōyō Soundtrack part 5 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_05"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part5.sh"
echo "Jōyō Soundtrack part 6 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_06"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part6.sh"
echo "Jōyō Soundtrack part 7 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_07"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part7.sh"
echo "Jōyō Soundtrack part 8 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_08"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part8.sh"
echo "Jōyō Soundtrack part 9 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_09"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part9.sh"
echo "Jōyō Soundtrack part 10 (100): http://localhost:${PORT}/exhibition.html?collection=post_elementary_10"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part10.sh"
echo "Jōyō Soundtrack part 11 (109): http://localhost:${PORT}/exhibition.html?collection=post_elementary_11"
echo "  Build:      ./scripts/prepare_post_elementary_obs_recording_part11.sh"
echo "Grade 1 Soundtrack part 1 (40): http://localhost:${PORT}/exhibition.html?collection=grade_1_01"
echo "  Build:      ./scripts/prepare_grade_1_obs_recording_part1.sh"
echo "Grade 1 Soundtrack part 2 (40): http://localhost:${PORT}/exhibition.html?collection=grade_1_02"
echo "  Build:      ./scripts/prepare_grade_1_obs_recording_part2.sh"
echo "Grade 1 Stroke Order part 1 (20): http://localhost:${PORT}/exhibition.html?collection=grade_1_strokes_01"
echo "Grade 1 Stroke Order part 2 (20): http://localhost:${PORT}/exhibition.html?collection=grade_1_strokes_02"
echo "Grade 1 Stroke Order part 3 (20): http://localhost:${PORT}/exhibition.html?collection=grade_1_strokes_03"
echo "Grade 1 Stroke Order part 4 (20): http://localhost:${PORT}/exhibition.html?collection=grade_1_strokes_04"
echo "  Quick QA:   add &exhibit=0&singleExhibit=1&timingScale=0.05"
echo "  Build:      python3 scripts/build_grade_1_stroke_order_exhibition.py --all"
echo "  Batch plan: python3 scripts/build_grade_1_stroke_order_exhibition.py --plan"
echo "Grade 2 Stroke Order part 1 (20): http://localhost:${PORT}/exhibition.html?collection=grade_2_strokes_01"
echo "Grade 2 Stroke Order part 8 (21): http://localhost:${PORT}/exhibition.html?collection=grade_2_strokes_08"
echo "  Build:      python3 scripts/build_grade_2_stroke_order_exhibition.py --all"
echo "  Batch plan: python3 scripts/build_grade_2_stroke_order_exhibition.py --plan"
echo "Grade 2 Soundtrack part 1 (40): http://localhost:${PORT}/exhibition.html?collection=grade_2_01"
echo "  Build:      ./scripts/prepare_grade_2_obs_recording_part1.sh"
echo "Grade 2 Soundtrack part 2 (40): http://localhost:${PORT}/exhibition.html?collection=grade_2_02"
echo "  Build:      ./scripts/prepare_grade_2_obs_recording_part2.sh"
echo "Grade 2 Soundtrack part 3 (40): http://localhost:${PORT}/exhibition.html?collection=grade_2_03"
echo "  Build:      ./scripts/prepare_grade_2_obs_recording_part3.sh"
echo "Grade 2 Soundtrack part 4 (41): http://localhost:${PORT}/exhibition.html?collection=grade_2_04"
echo "  Build:      ./scripts/prepare_grade_2_obs_recording_part4.sh"
echo "Grade 3 Stroke Order part 1 (25): http://localhost:${PORT}/exhibition.html?collection=grade_3_strokes_01"
echo "Grade 3 Stroke Order part 8 (25): http://localhost:${PORT}/exhibition.html?collection=grade_3_strokes_08"
echo "  Quick QA:   add &exhibit=0&singleExhibit=1&timingScale=0.05"
echo "  Build:      python3 scripts/build_grade_3_stroke_order_exhibition.py --all"
echo "  Batch plan: python3 scripts/build_grade_3_stroke_order_exhibition.py --plan"
echo "  Record p1:  ./scripts/prepare_grade_3_stroke_recording_part1.sh"
echo "Grade 3 Compounds part 1 (20): http://localhost:${PORT}/exhibition.html?collection=grade_3_compounds_school_01"
echo "Grade 3 Compounds part 10 (20): http://localhost:${PORT}/exhibition.html?collection=grade_3_compounds_school_10"
echo "  Build:      python3 scripts/build_grade_3_compounds_school.py --all"
echo "  Batch plan: python3 scripts/build_grade_3_compounds_school.py --plan"
echo "  Record all: ./scripts/prepare_grade_3_compounds_school_recording.sh"
echo "Grade 3 Soundtrack part 1 (50): http://localhost:${PORT}/exhibition.html?collection=grade_3_01"
echo "  Build:      ./scripts/prepare_grade_3_obs_recording_part1.sh"
echo "Grade 3 Soundtrack part 2 (50): http://localhost:${PORT}/exhibition.html?collection=grade_3_02"
echo "  Build:      ./scripts/prepare_grade_3_obs_recording_part2.sh"
echo "Grade 3 Soundtrack part 3 (50): http://localhost:${PORT}/exhibition.html?collection=grade_3_03"
echo "  Build:      ./scripts/prepare_grade_3_obs_recording_part3.sh"
echo "Grade 3 Soundtrack part 4 (50): http://localhost:${PORT}/exhibition.html?collection=grade_3_04"
echo "  Build:      ./scripts/prepare_grade_3_obs_recording_part4.sh"
echo "Grade 4 visual prototype:     http://localhost:${PORT}/grade4-prototype.html"
echo "Grade 4 Soundtrack part 1 (46): http://localhost:${PORT}/exhibition.html?collection=grade_4_01"
echo "Grade 4 Soundtrack part 2 (47): http://localhost:${PORT}/exhibition.html?collection=grade_4_02"
echo "Grade 4 Soundtrack part 3 (49): http://localhost:${PORT}/exhibition.html?collection=grade_4_03"
echo "Grade 4 Soundtrack part 4 (60): http://localhost:${PORT}/exhibition.html?collection=grade_4_04"
echo "  Quick QA:   add &timingScale=0.05"
echo "  Build:      python3 scripts/build_grade_4_soundtrack.py --part 1"
echo "Grade 4 Stroke Order part 1 (25): http://localhost:${PORT}/exhibition.html?collection=grade_4_strokes_01"
echo "Grade 4 Stroke Order part 8 (26): http://localhost:${PORT}/exhibition.html?collection=grade_4_strokes_08"
echo "  Quick QA:   add &exhibit=0&singleExhibit=1&timingScale=0.05"
echo "  Build:      python3 scripts/build_grade_4_stroke_order_exhibition.py --all"
echo "  Batch plan: python3 scripts/build_grade_4_stroke_order_exhibition.py --plan"
echo "  Record all: ./scripts/run_grade_4_stroke_playwright.sh"
echo "Grade 4 Compounds part 1 (20): http://localhost:${PORT}/exhibition.html?collection=grade_4_compounds_school_01"
echo "Grade 4 Compounds part 10 (21): http://localhost:${PORT}/exhibition.html?collection=grade_4_compounds_school_10"
echo "  Build:      python3 scripts/build_grade_4_compounds_school.py --all"
echo "  Batch plan: python3 scripts/build_grade_4_compounds_school.py --plan"
echo "  Record all: ./scripts/prepare_grade_4_compounds_school_recording.sh"
echo "Grade 5 Stroke Order part 1 (25): http://localhost:${PORT}/exhibition.html?collection=grade_5_strokes_01"
echo "Grade 5 Stroke Order part 8 (18): http://localhost:${PORT}/exhibition.html?collection=grade_5_strokes_08"
echo "  Build:      python3 scripts/build_grade_5_stroke_order_exhibition.py --all"
echo "  Record all: ./scripts/run_grade_5_stroke_playwright.sh"
echo "Grade 5 Compounds part 1 (20): http://localhost:${PORT}/exhibition.html?collection=grade_5_compounds_school_01"
echo "Grade 5 Compounds part 10 (13): http://localhost:${PORT}/exhibition.html?collection=grade_5_compounds_school_10"
echo "  Build:      python3 scripts/build_grade_5_compounds_school.py --all"
echo "  Record all: ./scripts/prepare_grade_5_compounds_school_recording.sh"
echo "Playwright Heart (optional): ./scripts/record_heart_exhibition.sh"
python3 -m http.server "$PORT"
