"""Orchestration: load → validate → render → write."""

from __future__ import annotations

from pathlib import Path

from . import paths
from .loaders import load_book, load_lesson
from .render import (
    render_book_html,
    render_bookshelf_html,
    render_home_html,
    render_lesson_html,
)
from .validate import ValidationError, ensure_valid_lesson, project_status


def _write(relpath: str, html: str, root: Path | None = None) -> Path:
    root = root or paths.ROOT
    out = root / relpath
    out.parent.mkdir(parents=True, exist_ok=True)
    # Marker so authors know not to hand-edit
    banner = (
        "<!--\n"
        "  GENERATED by KML Publishing Engine v1 — do not edit by hand.\n"
        "  Source of truth: data/ lesson packs. Re-run: python -m publish build …\n"
        "-->\n"
    )
    if not html.lstrip().startswith("<!--"):
        html = banner + html
    else:
        html = banner + html
    out.write_text(html, encoding="utf-8")
    return out


def build_lesson(lesson_id: str, root: Path | None = None) -> Path:
    """
    Public API:
        build_lesson("lesson_001") → writes HTML from the pack
    """
    root = root or paths.ROOT
    lesson = load_lesson(lesson_id, root=root)
    ensure_valid_lesson(lesson_id, lesson)
    html = render_lesson_html(lesson, template_dir=root / "templates")
    return _write(lesson.output_relpath, html, root=root)


def build_book(book_id: str, root: Path | None = None) -> Path:
    """build_book("book_01") → book landing page from metadata."""
    root = root or paths.ROOT
    book = load_book(book_id, root=root)
    # Ensure indexed lessons with packs validate when present
    for ref in book.lessons:
        pack = root / "data" / "lessons" / ref.id
        if pack.is_dir() and (pack / "lesson.json").exists():
            lesson = load_lesson(ref.id, root=root)
            ensure_valid_lesson(ref.id, lesson)
    html = render_book_html(book, template_dir=root / "templates")
    return _write(book.output_relpath, html, root=root)


def build_site(root: Path | None = None) -> list[Path]:
    """Generate homepage + bookshelf (+ later sitemaps/feeds)."""
    root = root or paths.ROOT
    books_index = root / "data" / "books" / "index.json"
    written: list[Path] = []
    books = []
    if books_index.exists():
        import json

        data = json.loads(books_index.read_text(encoding="utf-8"))
        for row in data.get("books") or []:
            bid = row["id"]
            if (root / "data" / "books" / f"{bid}.json").exists():
                books.append(load_book(bid, root=root))
    html = render_home_html(books, template_dir=root / "templates")
    written.append(_write("index.html", html, root=root))
    shelf = render_bookshelf_html(books, template_dir=root / "templates")
    written.append(_write("books/index.html", shelf, root=root))
    return written


def build_all(root: Path | None = None) -> dict:
    """Validate & build every lesson pack + books + site home."""
    root = root or paths.ROOT
    lessons_dir = root / "data" / "lessons"
    results = {"lessons": [], "books": [], "site": [], "errors": []}

    for pack in sorted(lessons_dir.iterdir()):
        if not pack.is_dir() or not pack.name.startswith("lesson_"):
            continue
        try:
            path = build_lesson(pack.name, root=root)
            results["lessons"].append(str(path.relative_to(root)))
        except ValidationError as e:
            results["errors"].append({pack.name: e.messages})
        except Exception as e:  # noqa: BLE001 — surface in CLI
            results["errors"].append({pack.name: [str(e)]})

    books_dir = root / "data" / "books"
    for book_file in sorted(books_dir.glob("book_*.json")):
        bid = book_file.stem
        try:
            path = build_book(bid, root=root)
            results["books"].append(str(path.relative_to(root)))
        except ValidationError as e:
            results["errors"].append({bid: e.messages})
        except Exception as e:  # noqa: BLE001
            results["errors"].append({bid: [str(e)]})

    try:
        site_paths = build_site(root=root)
        results["site"] = [str(p.relative_to(root)) for p in site_paths]
    except Exception as e:  # noqa: BLE001
        results["errors"].append({"site": [str(e)]})

    results["status"] = project_status()
    return results
